[package]
name = "rustmatica"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[profile.no-opt]
inherits = "dev"
opt-level = 0

[features]
lists = ["dep:strum"]
chrono = ["dep:chrono"]
entity-list = []
default = ["lists", "chrono"]

[dependencies]
# TODO: use stable release when available
fastnbt = { git = "https://github.com/RubixDev/fastnbt", branch = "value-serde" }
flate2 = "1.0.23"
serde = "1.0.136"
strum = { version = "0.24.0", features = ["derive"], optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
chrono = { version = "0.4.19", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
chrono = { version = "0.4.19", features = ["wasmbind"], optional = true }
js-sys = "0.3.57"

[dev-dependencies]
wasm-bindgen-test = "0.3.30"
