[package]
name = "rustmatica"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[features]
lists = ["dep:strum"]
default = ["lists"]

[dependencies]
fastnbt = "2.0.1"
flate2 = "1.0.23"
serde = "1.0.136"
strum = { version = "0.24.0", features = ["derive"], optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.30"
