[package]
name = "rustmatica"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastnbt = "2.0.0-alpha"
flate2 = "1.0.23"
serde = "1.0.136"
bitvec = "1.0.0"
