[package]
name = "rustmatica"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.wasm-test]
inherits = "test"
opt-level = 1

[dependencies]
fastnbt = "2.0.0-alpha"
flate2 = "1.0.23"
serde = "1.0.136"
bitvec = "1.0.0"
strum = { version = "0.24.0", features = ["derive"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.30"
