use std::{borrow::Cow, collections::HashMap};

use super::types::*;

#[derive(Debug, Clone)]
pub enum BlockState<'a> {
    Air,
    Stone,
    Granite,
    PolishedGranite,
    Diorite,
    PolishedDiorite,
    Andesite,
    PolishedAndesite,
    GrassBlock { snowy: bool },
    Dirt,
    CoarseDirt,
    Podzol { snowy: bool },
    Cobblestone,
    OakPlanks,
    SprucePlanks,
    BirchPlanks,
    JunglePlanks,
    AcaciaPlanks,
    DarkOakPlanks,
    OakSapling { stage: u8 },
    SpruceSapling { stage: u8 },
    BirchSapling { stage: u8 },
    JungleSapling { stage: u8 },
    AcaciaSapling { stage: u8 },
    DarkOakSapling { stage: u8 },
    Bedrock,
    Water { level: u8 },
    Lava { level: u8 },
    Sand,
    RedSand,
    Gravel,
    GoldOre,
    DeepslateGoldOre,
    IronOre,
    DeepslateIronOre,
    CoalOre,
    DeepslateCoalOre,
    NetherGoldOre,
    OakLog { axis: Axis },
    SpruceLog { axis: Axis },
    BirchLog { axis: Axis },
    JungleLog { axis: Axis },
    AcaciaLog { axis: Axis },
    DarkOakLog { axis: Axis },
    StrippedSpruceLog { axis: Axis },
    StrippedBirchLog { axis: Axis },
    StrippedJungleLog { axis: Axis },
    StrippedAcaciaLog { axis: Axis },
    StrippedDarkOakLog { axis: Axis },
    StrippedOakLog { axis: Axis },
    OakWood { axis: Axis },
    SpruceWood { axis: Axis },
    BirchWood { axis: Axis },
    JungleWood { axis: Axis },
    AcaciaWood { axis: Axis },
    DarkOakWood { axis: Axis },
    StrippedOakWood { axis: Axis },
    StrippedSpruceWood { axis: Axis },
    StrippedBirchWood { axis: Axis },
    StrippedJungleWood { axis: Axis },
    StrippedAcaciaWood { axis: Axis },
    StrippedDarkOakWood { axis: Axis },
    OakLeaves { distance: u8, persistent: bool },
    SpruceLeaves { distance: u8, persistent: bool },
    BirchLeaves { distance: u8, persistent: bool },
    JungleLeaves { distance: u8, persistent: bool },
    AcaciaLeaves { distance: u8, persistent: bool },
    DarkOakLeaves { distance: u8, persistent: bool },
    AzaleaLeaves { distance: u8, persistent: bool },
    FloweringAzaleaLeaves { distance: u8, persistent: bool },
    Sponge,
    WetSponge,
    Glass,
    LapisOre,
    DeepslateLapisOre,
    LapisBlock,
    Dispenser { facing: Direction, triggered: bool },
    Sandstone,
    ChiseledSandstone,
    CutSandstone,
    NoteBlock { instrument: Instrument, note: u8, powered: bool },
    WhiteBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    OrangeBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    MagentaBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    LightBlueBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    YellowBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    LimeBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    PinkBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    GrayBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    LightGrayBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    CyanBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    PurpleBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    BlueBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    BrownBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    GreenBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    RedBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    BlackBed { facing: HorizontalDirection, occupied: bool, part: BedPart },
    PoweredRail { powered: bool, shape: RailShape, waterlogged: bool },
    DetectorRail { powered: bool, shape: RailShape, waterlogged: bool },
    StickyPiston { extended: bool, facing: Direction },
    Cobweb,
    Grass,
    Fern,
    DeadBush,
    Seagrass,
    TallSeagrass { half: DoubleBlockHalf },
    Piston { extended: bool, facing: Direction },
    PistonHead { facing: Direction, short: bool, r#type: PistonType },
    WhiteWool,
    OrangeWool,
    MagentaWool,
    LightBlueWool,
    YellowWool,
    LimeWool,
    PinkWool,
    GrayWool,
    LightGrayWool,
    CyanWool,
    PurpleWool,
    BlueWool,
    BrownWool,
    GreenWool,
    RedWool,
    BlackWool,
    MovingPiston { facing: Direction, r#type: PistonType },
    Dandelion,
    Poppy,
    BlueOrchid,
    Allium,
    AzureBluet,
    RedTulip,
    OrangeTulip,
    WhiteTulip,
    PinkTulip,
    OxeyeDaisy,
    Cornflower,
    WitherRose,
    LilyOfTheValley,
    BrownMushroom,
    RedMushroom,
    GoldBlock,
    IronBlock,
    Bricks,
    Tnt { unstable: bool },
    Bookshelf,
    MossyCobblestone,
    Obsidian,
    Torch,
    WallTorch { facing: HorizontalDirection },
    Fire { age: u8, east: bool, north: bool, south: bool, up: bool, west: bool },
    SoulFire,
    Spawner,
    OakStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    Chest { facing: HorizontalDirection, r#type: ChestType, waterlogged: bool },
    RedstoneWire { east: WireConnection, north: WireConnection, power: u8, south: WireConnection, west: WireConnection },
    DiamondOre,
    DeepslateDiamondOre,
    DiamondBlock,
    CraftingTable,
    Wheat { age: u8 },
    Farmland { moisture: u8 },
    Furnace { facing: HorizontalDirection, lit: bool },
    OakSign { rotation: u8, waterlogged: bool },
    SpruceSign { rotation: u8, waterlogged: bool },
    BirchSign { rotation: u8, waterlogged: bool },
    AcaciaSign { rotation: u8, waterlogged: bool },
    JungleSign { rotation: u8, waterlogged: bool },
    DarkOakSign { rotation: u8, waterlogged: bool },
    OakDoor { facing: HorizontalDirection, half: DoubleBlockHalf, hinge: DoorHinge, open: bool, powered: bool },
    Ladder { facing: HorizontalDirection, waterlogged: bool },
    Rail { shape: RailShape, waterlogged: bool },
    CobblestoneStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    OakWallSign { facing: HorizontalDirection, waterlogged: bool },
    SpruceWallSign { facing: HorizontalDirection, waterlogged: bool },
    BirchWallSign { facing: HorizontalDirection, waterlogged: bool },
    AcaciaWallSign { facing: HorizontalDirection, waterlogged: bool },
    JungleWallSign { facing: HorizontalDirection, waterlogged: bool },
    DarkOakWallSign { facing: HorizontalDirection, waterlogged: bool },
    Lever { face: WallMountLocation, facing: HorizontalDirection, powered: bool },
    StonePressurePlate { powered: bool },
    IronDoor { facing: HorizontalDirection, half: DoubleBlockHalf, hinge: DoorHinge, open: bool, powered: bool },
    OakPressurePlate { powered: bool },
    SprucePressurePlate { powered: bool },
    BirchPressurePlate { powered: bool },
    JunglePressurePlate { powered: bool },
    AcaciaPressurePlate { powered: bool },
    DarkOakPressurePlate { powered: bool },
    RedstoneOre { lit: bool },
    DeepslateRedstoneOre { lit: bool },
    RedstoneTorch { lit: bool },
    RedstoneWallTorch { facing: HorizontalDirection, lit: bool },
    StoneButton { face: WallMountLocation, facing: HorizontalDirection, powered: bool },
    Snow { layers: u8 },
    Ice,
    SnowBlock,
    Cactus { age: u8 },
    Clay,
    SugarCane { age: u8 },
    Jukebox { has_record: bool },
    OakFence { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    Pumpkin,
    Netherrack,
    SoulSand,
    SoulSoil,
    Basalt { axis: Axis },
    PolishedBasalt { axis: Axis },
    SoulTorch,
    SoulWallTorch { facing: HorizontalDirection },
    Glowstone,
    NetherPortal { axis: HorizontalAxis },
    CarvedPumpkin { facing: HorizontalDirection },
    JackOLantern { facing: HorizontalDirection },
    Cake { bites: u8 },
    Repeater { delay: u8, facing: HorizontalDirection, locked: bool, powered: bool },
    WhiteStainedGlass,
    OrangeStainedGlass,
    MagentaStainedGlass,
    LightBlueStainedGlass,
    YellowStainedGlass,
    LimeStainedGlass,
    PinkStainedGlass,
    GrayStainedGlass,
    LightGrayStainedGlass,
    CyanStainedGlass,
    PurpleStainedGlass,
    BlueStainedGlass,
    BrownStainedGlass,
    GreenStainedGlass,
    RedStainedGlass,
    BlackStainedGlass,
    OakTrapdoor { facing: HorizontalDirection, half: BlockHalf, open: bool, powered: bool, waterlogged: bool },
    SpruceTrapdoor { facing: HorizontalDirection, half: BlockHalf, open: bool, powered: bool, waterlogged: bool },
    BirchTrapdoor { facing: HorizontalDirection, half: BlockHalf, open: bool, powered: bool, waterlogged: bool },
    JungleTrapdoor { facing: HorizontalDirection, half: BlockHalf, open: bool, powered: bool, waterlogged: bool },
    AcaciaTrapdoor { facing: HorizontalDirection, half: BlockHalf, open: bool, powered: bool, waterlogged: bool },
    DarkOakTrapdoor { facing: HorizontalDirection, half: BlockHalf, open: bool, powered: bool, waterlogged: bool },
    StoneBricks,
    MossyStoneBricks,
    CrackedStoneBricks,
    ChiseledStoneBricks,
    InfestedStone,
    InfestedCobblestone,
    InfestedStoneBricks,
    InfestedMossyStoneBricks,
    InfestedCrackedStoneBricks,
    InfestedChiseledStoneBricks,
    BrownMushroomBlock { down: bool, east: bool, north: bool, south: bool, up: bool, west: bool },
    RedMushroomBlock { down: bool, east: bool, north: bool, south: bool, up: bool, west: bool },
    MushroomStem { down: bool, east: bool, north: bool, south: bool, up: bool, west: bool },
    IronBars { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    Chain { axis: Axis, waterlogged: bool },
    GlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    Melon,
    AttachedPumpkinStem { facing: HorizontalDirection },
    AttachedMelonStem { facing: HorizontalDirection },
    PumpkinStem { age: u8 },
    MelonStem { age: u8 },
    Vine { east: bool, north: bool, south: bool, up: bool, west: bool },
    GlowLichen { down: bool, east: bool, north: bool, south: bool, up: bool, waterlogged: bool, west: bool },
    OakFenceGate { facing: HorizontalDirection, in_wall: bool, open: bool, powered: bool },
    BrickStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    StoneBrickStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    Mycelium { snowy: bool },
    LilyPad,
    NetherBricks,
    NetherBrickFence { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    NetherBrickStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    NetherWart { age: u8 },
    EnchantingTable,
    BrewingStand { has_bottle_0: bool, has_bottle_1: bool, has_bottle_2: bool },
    Cauldron,
    WaterCauldron { level: u8 },
    LavaCauldron,
    PowderSnowCauldron { level: u8 },
    EndPortal,
    EndPortalFrame { eye: bool, facing: HorizontalDirection },
    EndStone,
    DragonEgg,
    RedstoneLamp { lit: bool },
    Cocoa { age: u8, facing: HorizontalDirection },
    SandstoneStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    EmeraldOre,
    DeepslateEmeraldOre,
    EnderChest { facing: HorizontalDirection, waterlogged: bool },
    TripwireHook { attached: bool, facing: HorizontalDirection, powered: bool },
    Tripwire { attached: bool, disarmed: bool, east: bool, north: bool, powered: bool, south: bool, west: bool },
    EmeraldBlock,
    SpruceStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    BirchStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    JungleStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    CommandBlock { conditional: bool, facing: Direction },
    Beacon,
    CobblestoneWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    MossyCobblestoneWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    FlowerPot,
    PottedOakSapling,
    PottedSpruceSapling,
    PottedBirchSapling,
    PottedJungleSapling,
    PottedAcaciaSapling,
    PottedDarkOakSapling,
    PottedFern,
    PottedDandelion,
    PottedPoppy,
    PottedBlueOrchid,
    PottedAllium,
    PottedAzureBluet,
    PottedRedTulip,
    PottedOrangeTulip,
    PottedWhiteTulip,
    PottedPinkTulip,
    PottedOxeyeDaisy,
    PottedCornflower,
    PottedLilyOfTheValley,
    PottedWitherRose,
    PottedRedMushroom,
    PottedBrownMushroom,
    PottedDeadBush,
    PottedCactus,
    Carrots { age: u8 },
    Potatoes { age: u8 },
    OakButton { face: WallMountLocation, facing: HorizontalDirection, powered: bool },
    SpruceButton { face: WallMountLocation, facing: HorizontalDirection, powered: bool },
    BirchButton { face: WallMountLocation, facing: HorizontalDirection, powered: bool },
    JungleButton { face: WallMountLocation, facing: HorizontalDirection, powered: bool },
    AcaciaButton { face: WallMountLocation, facing: HorizontalDirection, powered: bool },
    DarkOakButton { face: WallMountLocation, facing: HorizontalDirection, powered: bool },
    SkeletonSkull { rotation: u8 },
    SkeletonWallSkull { facing: HorizontalDirection },
    WitherSkeletonSkull { rotation: u8 },
    WitherSkeletonWallSkull { facing: HorizontalDirection },
    ZombieHead { rotation: u8 },
    ZombieWallHead { facing: HorizontalDirection },
    PlayerHead { rotation: u8 },
    PlayerWallHead { facing: HorizontalDirection },
    CreeperHead { rotation: u8 },
    CreeperWallHead { facing: HorizontalDirection },
    DragonHead { rotation: u8 },
    DragonWallHead { facing: HorizontalDirection },
    Anvil { facing: HorizontalDirection },
    ChippedAnvil { facing: HorizontalDirection },
    DamagedAnvil { facing: HorizontalDirection },
    TrappedChest { facing: HorizontalDirection, r#type: ChestType, waterlogged: bool },
    LightWeightedPressurePlate { power: u8 },
    HeavyWeightedPressurePlate { power: u8 },
    Comparator { facing: HorizontalDirection, mode: ComparatorMode, powered: bool },
    DaylightDetector { inverted: bool, power: u8 },
    RedstoneBlock,
    NetherQuartzOre,
    Hopper { enabled: bool, facing: HopperDirection },
    QuartzBlock,
    ChiseledQuartzBlock,
    QuartzPillar { axis: Axis },
    QuartzStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    ActivatorRail { powered: bool, shape: RailShape, waterlogged: bool },
    Dropper { facing: Direction, triggered: bool },
    WhiteTerracotta,
    OrangeTerracotta,
    MagentaTerracotta,
    LightBlueTerracotta,
    YellowTerracotta,
    LimeTerracotta,
    PinkTerracotta,
    GrayTerracotta,
    LightGrayTerracotta,
    CyanTerracotta,
    PurpleTerracotta,
    BlueTerracotta,
    BrownTerracotta,
    GreenTerracotta,
    RedTerracotta,
    BlackTerracotta,
    WhiteStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    OrangeStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    MagentaStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    LightBlueStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    YellowStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    LimeStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    PinkStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    GrayStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    LightGrayStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    CyanStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    PurpleStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    BlueStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    BrownStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    GreenStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    RedStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    BlackStainedGlassPane { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    AcaciaStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    DarkOakStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    SlimeBlock,
    Barrier,
    Light { level: u8, waterlogged: bool },
    IronTrapdoor { facing: HorizontalDirection, half: BlockHalf, open: bool, powered: bool, waterlogged: bool },
    Prismarine,
    PrismarineBricks,
    DarkPrismarine,
    PrismarineStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    PrismarineBrickStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    DarkPrismarineStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    PrismarineSlab { r#type: SlabType, waterlogged: bool },
    PrismarineBrickSlab { r#type: SlabType, waterlogged: bool },
    DarkPrismarineSlab { r#type: SlabType, waterlogged: bool },
    SeaLantern,
    HayBlock { axis: Axis },
    WhiteCarpet,
    OrangeCarpet,
    MagentaCarpet,
    LightBlueCarpet,
    YellowCarpet,
    LimeCarpet,
    PinkCarpet,
    GrayCarpet,
    LightGrayCarpet,
    CyanCarpet,
    PurpleCarpet,
    BlueCarpet,
    BrownCarpet,
    GreenCarpet,
    RedCarpet,
    BlackCarpet,
    Terracotta,
    CoalBlock,
    PackedIce,
    Sunflower { half: DoubleBlockHalf },
    Lilac { half: DoubleBlockHalf },
    RoseBush { half: DoubleBlockHalf },
    Peony { half: DoubleBlockHalf },
    TallGrass { half: DoubleBlockHalf },
    LargeFern { half: DoubleBlockHalf },
    WhiteBanner { rotation: u8 },
    OrangeBanner { rotation: u8 },
    MagentaBanner { rotation: u8 },
    LightBlueBanner { rotation: u8 },
    YellowBanner { rotation: u8 },
    LimeBanner { rotation: u8 },
    PinkBanner { rotation: u8 },
    GrayBanner { rotation: u8 },
    LightGrayBanner { rotation: u8 },
    CyanBanner { rotation: u8 },
    PurpleBanner { rotation: u8 },
    BlueBanner { rotation: u8 },
    BrownBanner { rotation: u8 },
    GreenBanner { rotation: u8 },
    RedBanner { rotation: u8 },
    BlackBanner { rotation: u8 },
    WhiteWallBanner { facing: HorizontalDirection },
    OrangeWallBanner { facing: HorizontalDirection },
    MagentaWallBanner { facing: HorizontalDirection },
    LightBlueWallBanner { facing: HorizontalDirection },
    YellowWallBanner { facing: HorizontalDirection },
    LimeWallBanner { facing: HorizontalDirection },
    PinkWallBanner { facing: HorizontalDirection },
    GrayWallBanner { facing: HorizontalDirection },
    LightGrayWallBanner { facing: HorizontalDirection },
    CyanWallBanner { facing: HorizontalDirection },
    PurpleWallBanner { facing: HorizontalDirection },
    BlueWallBanner { facing: HorizontalDirection },
    BrownWallBanner { facing: HorizontalDirection },
    GreenWallBanner { facing: HorizontalDirection },
    RedWallBanner { facing: HorizontalDirection },
    BlackWallBanner { facing: HorizontalDirection },
    RedSandstone,
    ChiseledRedSandstone,
    CutRedSandstone,
    RedSandstoneStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    OakSlab { r#type: SlabType, waterlogged: bool },
    SpruceSlab { r#type: SlabType, waterlogged: bool },
    BirchSlab { r#type: SlabType, waterlogged: bool },
    JungleSlab { r#type: SlabType, waterlogged: bool },
    AcaciaSlab { r#type: SlabType, waterlogged: bool },
    DarkOakSlab { r#type: SlabType, waterlogged: bool },
    StoneSlab { r#type: SlabType, waterlogged: bool },
    SmoothStoneSlab { r#type: SlabType, waterlogged: bool },
    SandstoneSlab { r#type: SlabType, waterlogged: bool },
    CutSandstoneSlab { r#type: SlabType, waterlogged: bool },
    PetrifiedOakSlab { r#type: SlabType, waterlogged: bool },
    CobblestoneSlab { r#type: SlabType, waterlogged: bool },
    BrickSlab { r#type: SlabType, waterlogged: bool },
    StoneBrickSlab { r#type: SlabType, waterlogged: bool },
    NetherBrickSlab { r#type: SlabType, waterlogged: bool },
    QuartzSlab { r#type: SlabType, waterlogged: bool },
    RedSandstoneSlab { r#type: SlabType, waterlogged: bool },
    CutRedSandstoneSlab { r#type: SlabType, waterlogged: bool },
    PurpurSlab { r#type: SlabType, waterlogged: bool },
    SmoothStone,
    SmoothSandstone,
    SmoothQuartz,
    SmoothRedSandstone,
    SpruceFenceGate { facing: HorizontalDirection, in_wall: bool, open: bool, powered: bool },
    BirchFenceGate { facing: HorizontalDirection, in_wall: bool, open: bool, powered: bool },
    JungleFenceGate { facing: HorizontalDirection, in_wall: bool, open: bool, powered: bool },
    AcaciaFenceGate { facing: HorizontalDirection, in_wall: bool, open: bool, powered: bool },
    DarkOakFenceGate { facing: HorizontalDirection, in_wall: bool, open: bool, powered: bool },
    SpruceFence { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    BirchFence { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    JungleFence { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    AcaciaFence { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    DarkOakFence { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    SpruceDoor { facing: HorizontalDirection, half: DoubleBlockHalf, hinge: DoorHinge, open: bool, powered: bool },
    BirchDoor { facing: HorizontalDirection, half: DoubleBlockHalf, hinge: DoorHinge, open: bool, powered: bool },
    JungleDoor { facing: HorizontalDirection, half: DoubleBlockHalf, hinge: DoorHinge, open: bool, powered: bool },
    AcaciaDoor { facing: HorizontalDirection, half: DoubleBlockHalf, hinge: DoorHinge, open: bool, powered: bool },
    DarkOakDoor { facing: HorizontalDirection, half: DoubleBlockHalf, hinge: DoorHinge, open: bool, powered: bool },
    EndRod { facing: Direction },
    ChorusPlant { down: bool, east: bool, north: bool, south: bool, up: bool, west: bool },
    ChorusFlower { age: u8 },
    PurpurBlock,
    PurpurPillar { axis: Axis },
    PurpurStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    EndStoneBricks,
    Beetroots { age: u8 },
    DirtPath,
    EndGateway,
    RepeatingCommandBlock { conditional: bool, facing: Direction },
    ChainCommandBlock { conditional: bool, facing: Direction },
    FrostedIce { age: u8 },
    MagmaBlock,
    NetherWartBlock,
    RedNetherBricks,
    BoneBlock { axis: Axis },
    StructureVoid,
    Observer { facing: Direction, powered: bool },
    ShulkerBox { facing: Direction },
    WhiteShulkerBox { facing: Direction },
    OrangeShulkerBox { facing: Direction },
    MagentaShulkerBox { facing: Direction },
    LightBlueShulkerBox { facing: Direction },
    YellowShulkerBox { facing: Direction },
    LimeShulkerBox { facing: Direction },
    PinkShulkerBox { facing: Direction },
    GrayShulkerBox { facing: Direction },
    LightGrayShulkerBox { facing: Direction },
    CyanShulkerBox { facing: Direction },
    PurpleShulkerBox { facing: Direction },
    BlueShulkerBox { facing: Direction },
    BrownShulkerBox { facing: Direction },
    GreenShulkerBox { facing: Direction },
    RedShulkerBox { facing: Direction },
    BlackShulkerBox { facing: Direction },
    WhiteGlazedTerracotta { facing: HorizontalDirection },
    OrangeGlazedTerracotta { facing: HorizontalDirection },
    MagentaGlazedTerracotta { facing: HorizontalDirection },
    LightBlueGlazedTerracotta { facing: HorizontalDirection },
    YellowGlazedTerracotta { facing: HorizontalDirection },
    LimeGlazedTerracotta { facing: HorizontalDirection },
    PinkGlazedTerracotta { facing: HorizontalDirection },
    GrayGlazedTerracotta { facing: HorizontalDirection },
    LightGrayGlazedTerracotta { facing: HorizontalDirection },
    CyanGlazedTerracotta { facing: HorizontalDirection },
    PurpleGlazedTerracotta { facing: HorizontalDirection },
    BlueGlazedTerracotta { facing: HorizontalDirection },
    BrownGlazedTerracotta { facing: HorizontalDirection },
    GreenGlazedTerracotta { facing: HorizontalDirection },
    RedGlazedTerracotta { facing: HorizontalDirection },
    BlackGlazedTerracotta { facing: HorizontalDirection },
    WhiteConcrete,
    OrangeConcrete,
    MagentaConcrete,
    LightBlueConcrete,
    YellowConcrete,
    LimeConcrete,
    PinkConcrete,
    GrayConcrete,
    LightGrayConcrete,
    CyanConcrete,
    PurpleConcrete,
    BlueConcrete,
    BrownConcrete,
    GreenConcrete,
    RedConcrete,
    BlackConcrete,
    WhiteConcretePowder,
    OrangeConcretePowder,
    MagentaConcretePowder,
    LightBlueConcretePowder,
    YellowConcretePowder,
    LimeConcretePowder,
    PinkConcretePowder,
    GrayConcretePowder,
    LightGrayConcretePowder,
    CyanConcretePowder,
    PurpleConcretePowder,
    BlueConcretePowder,
    BrownConcretePowder,
    GreenConcretePowder,
    RedConcretePowder,
    BlackConcretePowder,
    Kelp { age: u8 },
    KelpPlant,
    DriedKelpBlock,
    TurtleEgg { eggs: u8, hatch: u8 },
    DeadTubeCoralBlock,
    DeadBrainCoralBlock,
    DeadBubbleCoralBlock,
    DeadFireCoralBlock,
    DeadHornCoralBlock,
    TubeCoralBlock,
    BrainCoralBlock,
    BubbleCoralBlock,
    FireCoralBlock,
    HornCoralBlock,
    DeadTubeCoral { waterlogged: bool },
    DeadBrainCoral { waterlogged: bool },
    DeadBubbleCoral { waterlogged: bool },
    DeadFireCoral { waterlogged: bool },
    DeadHornCoral { waterlogged: bool },
    TubeCoral { waterlogged: bool },
    BrainCoral { waterlogged: bool },
    BubbleCoral { waterlogged: bool },
    FireCoral { waterlogged: bool },
    HornCoral { waterlogged: bool },
    DeadTubeCoralFan { waterlogged: bool },
    DeadBrainCoralFan { waterlogged: bool },
    DeadBubbleCoralFan { waterlogged: bool },
    DeadFireCoralFan { waterlogged: bool },
    DeadHornCoralFan { waterlogged: bool },
    TubeCoralFan { waterlogged: bool },
    BrainCoralFan { waterlogged: bool },
    BubbleCoralFan { waterlogged: bool },
    FireCoralFan { waterlogged: bool },
    HornCoralFan { waterlogged: bool },
    DeadTubeCoralWallFan { facing: HorizontalDirection, waterlogged: bool },
    DeadBrainCoralWallFan { facing: HorizontalDirection, waterlogged: bool },
    DeadBubbleCoralWallFan { facing: HorizontalDirection, waterlogged: bool },
    DeadFireCoralWallFan { facing: HorizontalDirection, waterlogged: bool },
    DeadHornCoralWallFan { facing: HorizontalDirection, waterlogged: bool },
    TubeCoralWallFan { facing: HorizontalDirection, waterlogged: bool },
    BrainCoralWallFan { facing: HorizontalDirection, waterlogged: bool },
    BubbleCoralWallFan { facing: HorizontalDirection, waterlogged: bool },
    FireCoralWallFan { facing: HorizontalDirection, waterlogged: bool },
    HornCoralWallFan { facing: HorizontalDirection, waterlogged: bool },
    SeaPickle { pickles: u8, waterlogged: bool },
    BlueIce,
    Conduit { waterlogged: bool },
    BambooSapling,
    Bamboo { age: u8, leaves: BambooLeaves, stage: u8 },
    PottedBamboo,
    VoidAir,
    CaveAir,
    BubbleColumn { drag: bool },
    PolishedGraniteStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    SmoothRedSandstoneStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    MossyStoneBrickStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    PolishedDioriteStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    MossyCobblestoneStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    EndStoneBrickStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    StoneStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    SmoothSandstoneStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    SmoothQuartzStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    GraniteStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    AndesiteStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    RedNetherBrickStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    PolishedAndesiteStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    DioriteStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    PolishedGraniteSlab { r#type: SlabType, waterlogged: bool },
    SmoothRedSandstoneSlab { r#type: SlabType, waterlogged: bool },
    MossyStoneBrickSlab { r#type: SlabType, waterlogged: bool },
    PolishedDioriteSlab { r#type: SlabType, waterlogged: bool },
    MossyCobblestoneSlab { r#type: SlabType, waterlogged: bool },
    EndStoneBrickSlab { r#type: SlabType, waterlogged: bool },
    SmoothSandstoneSlab { r#type: SlabType, waterlogged: bool },
    SmoothQuartzSlab { r#type: SlabType, waterlogged: bool },
    GraniteSlab { r#type: SlabType, waterlogged: bool },
    AndesiteSlab { r#type: SlabType, waterlogged: bool },
    RedNetherBrickSlab { r#type: SlabType, waterlogged: bool },
    PolishedAndesiteSlab { r#type: SlabType, waterlogged: bool },
    DioriteSlab { r#type: SlabType, waterlogged: bool },
    BrickWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    PrismarineWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    RedSandstoneWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    MossyStoneBrickWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    GraniteWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    StoneBrickWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    NetherBrickWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    AndesiteWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    RedNetherBrickWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    SandstoneWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    EndStoneBrickWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    DioriteWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    Scaffolding { bottom: bool, distance: u8, waterlogged: bool },
    Loom { facing: HorizontalDirection },
    Barrel { facing: Direction, open: bool },
    Smoker { facing: HorizontalDirection, lit: bool },
    BlastFurnace { facing: HorizontalDirection, lit: bool },
    CartographyTable,
    FletchingTable,
    Grindstone { face: WallMountLocation, facing: HorizontalDirection },
    Lectern { facing: HorizontalDirection, has_book: bool, powered: bool },
    SmithingTable,
    Stonecutter { facing: HorizontalDirection },
    Bell { attachment: Attachment, facing: HorizontalDirection, powered: bool },
    Lantern { hanging: bool, waterlogged: bool },
    SoulLantern { hanging: bool, waterlogged: bool },
    Campfire { facing: HorizontalDirection, lit: bool, signal_fire: bool, waterlogged: bool },
    SoulCampfire { facing: HorizontalDirection, lit: bool, signal_fire: bool, waterlogged: bool },
    SweetBerryBush { age: u8 },
    WarpedStem { axis: Axis },
    StrippedWarpedStem { axis: Axis },
    WarpedHyphae { axis: Axis },
    StrippedWarpedHyphae { axis: Axis },
    WarpedNylium,
    WarpedFungus,
    WarpedWartBlock,
    WarpedRoots,
    NetherSprouts,
    CrimsonStem { axis: Axis },
    StrippedCrimsonStem { axis: Axis },
    CrimsonHyphae { axis: Axis },
    StrippedCrimsonHyphae { axis: Axis },
    CrimsonNylium,
    CrimsonFungus,
    Shroomlight,
    WeepingVines { age: u8 },
    WeepingVinesPlant,
    TwistingVines { age: u8 },
    TwistingVinesPlant,
    CrimsonRoots,
    CrimsonPlanks,
    WarpedPlanks,
    CrimsonSlab { r#type: SlabType, waterlogged: bool },
    WarpedSlab { r#type: SlabType, waterlogged: bool },
    CrimsonPressurePlate { powered: bool },
    WarpedPressurePlate { powered: bool },
    CrimsonFence { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    WarpedFence { east: bool, north: bool, south: bool, waterlogged: bool, west: bool },
    CrimsonTrapdoor { facing: HorizontalDirection, half: BlockHalf, open: bool, powered: bool, waterlogged: bool },
    WarpedTrapdoor { facing: HorizontalDirection, half: BlockHalf, open: bool, powered: bool, waterlogged: bool },
    CrimsonFenceGate { facing: HorizontalDirection, in_wall: bool, open: bool, powered: bool },
    WarpedFenceGate { facing: HorizontalDirection, in_wall: bool, open: bool, powered: bool },
    CrimsonStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    WarpedStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    CrimsonButton { face: WallMountLocation, facing: HorizontalDirection, powered: bool },
    WarpedButton { face: WallMountLocation, facing: HorizontalDirection, powered: bool },
    CrimsonDoor { facing: HorizontalDirection, half: DoubleBlockHalf, hinge: DoorHinge, open: bool, powered: bool },
    WarpedDoor { facing: HorizontalDirection, half: DoubleBlockHalf, hinge: DoorHinge, open: bool, powered: bool },
    CrimsonSign { rotation: u8, waterlogged: bool },
    WarpedSign { rotation: u8, waterlogged: bool },
    CrimsonWallSign { facing: HorizontalDirection, waterlogged: bool },
    WarpedWallSign { facing: HorizontalDirection, waterlogged: bool },
    StructureBlock { mode: StructureBlockMode },
    Jigsaw { orientation: Orientation },
    Composter { level: u8 },
    Target { power: u8 },
    BeeNest { facing: HorizontalDirection, honey_level: u8 },
    Beehive { facing: HorizontalDirection, honey_level: u8 },
    HoneyBlock,
    HoneycombBlock,
    NetheriteBlock,
    AncientDebris,
    CryingObsidian,
    RespawnAnchor { charges: u8 },
    PottedCrimsonFungus,
    PottedWarpedFungus,
    PottedCrimsonRoots,
    PottedWarpedRoots,
    Lodestone,
    Blackstone,
    BlackstoneStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    BlackstoneWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    BlackstoneSlab { r#type: SlabType, waterlogged: bool },
    PolishedBlackstone,
    PolishedBlackstoneBricks,
    CrackedPolishedBlackstoneBricks,
    ChiseledPolishedBlackstone,
    PolishedBlackstoneBrickSlab { r#type: SlabType, waterlogged: bool },
    PolishedBlackstoneBrickStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    PolishedBlackstoneBrickWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    GildedBlackstone,
    PolishedBlackstoneStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    PolishedBlackstoneSlab { r#type: SlabType, waterlogged: bool },
    PolishedBlackstonePressurePlate { powered: bool },
    PolishedBlackstoneButton { face: WallMountLocation, facing: HorizontalDirection, powered: bool },
    PolishedBlackstoneWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    ChiseledNetherBricks,
    CrackedNetherBricks,
    QuartzBricks,
    Candle { candles: u8, lit: bool, waterlogged: bool },
    WhiteCandle { candles: u8, lit: bool, waterlogged: bool },
    OrangeCandle { candles: u8, lit: bool, waterlogged: bool },
    MagentaCandle { candles: u8, lit: bool, waterlogged: bool },
    LightBlueCandle { candles: u8, lit: bool, waterlogged: bool },
    YellowCandle { candles: u8, lit: bool, waterlogged: bool },
    LimeCandle { candles: u8, lit: bool, waterlogged: bool },
    PinkCandle { candles: u8, lit: bool, waterlogged: bool },
    GrayCandle { candles: u8, lit: bool, waterlogged: bool },
    LightGrayCandle { candles: u8, lit: bool, waterlogged: bool },
    CyanCandle { candles: u8, lit: bool, waterlogged: bool },
    PurpleCandle { candles: u8, lit: bool, waterlogged: bool },
    BlueCandle { candles: u8, lit: bool, waterlogged: bool },
    BrownCandle { candles: u8, lit: bool, waterlogged: bool },
    GreenCandle { candles: u8, lit: bool, waterlogged: bool },
    RedCandle { candles: u8, lit: bool, waterlogged: bool },
    BlackCandle { candles: u8, lit: bool, waterlogged: bool },
    CandleCake { lit: bool },
    WhiteCandleCake { lit: bool },
    OrangeCandleCake { lit: bool },
    MagentaCandleCake { lit: bool },
    LightBlueCandleCake { lit: bool },
    YellowCandleCake { lit: bool },
    LimeCandleCake { lit: bool },
    PinkCandleCake { lit: bool },
    GrayCandleCake { lit: bool },
    LightGrayCandleCake { lit: bool },
    CyanCandleCake { lit: bool },
    PurpleCandleCake { lit: bool },
    BlueCandleCake { lit: bool },
    BrownCandleCake { lit: bool },
    GreenCandleCake { lit: bool },
    RedCandleCake { lit: bool },
    BlackCandleCake { lit: bool },
    AmethystBlock,
    BuddingAmethyst,
    AmethystCluster { facing: Direction, waterlogged: bool },
    LargeAmethystBud { facing: Direction, waterlogged: bool },
    MediumAmethystBud { facing: Direction, waterlogged: bool },
    SmallAmethystBud { facing: Direction, waterlogged: bool },
    Tuff,
    Calcite,
    TintedGlass,
    PowderSnow,
    SculkSensor { power: u8, sculk_sensor_phase: SculkSensorPhase, waterlogged: bool },
    OxidizedCopper,
    WeatheredCopper,
    ExposedCopper,
    CopperBlock,
    CopperOre,
    DeepslateCopperOre,
    OxidizedCutCopper,
    WeatheredCutCopper,
    ExposedCutCopper,
    CutCopper,
    OxidizedCutCopperStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    WeatheredCutCopperStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    ExposedCutCopperStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    CutCopperStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    OxidizedCutCopperSlab { r#type: SlabType, waterlogged: bool },
    WeatheredCutCopperSlab { r#type: SlabType, waterlogged: bool },
    ExposedCutCopperSlab { r#type: SlabType, waterlogged: bool },
    CutCopperSlab { r#type: SlabType, waterlogged: bool },
    WaxedCopperBlock,
    WaxedWeatheredCopper,
    WaxedExposedCopper,
    WaxedOxidizedCopper,
    WaxedOxidizedCutCopper,
    WaxedWeatheredCutCopper,
    WaxedExposedCutCopper,
    WaxedCutCopper,
    WaxedOxidizedCutCopperStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    WaxedWeatheredCutCopperStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    WaxedExposedCutCopperStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    WaxedCutCopperStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    WaxedOxidizedCutCopperSlab { r#type: SlabType, waterlogged: bool },
    WaxedWeatheredCutCopperSlab { r#type: SlabType, waterlogged: bool },
    WaxedExposedCutCopperSlab { r#type: SlabType, waterlogged: bool },
    WaxedCutCopperSlab { r#type: SlabType, waterlogged: bool },
    LightningRod { facing: Direction, powered: bool, waterlogged: bool },
    PointedDripstone { thickness: Thickness, vertical_direction: VerticalDirection, waterlogged: bool },
    DripstoneBlock,
    CaveVines { age: u8, berries: bool },
    CaveVinesPlant { berries: bool },
    SporeBlossom,
    Azalea,
    FloweringAzalea,
    MossCarpet,
    MossBlock,
    BigDripleaf { facing: HorizontalDirection, tilt: Tilt, waterlogged: bool },
    BigDripleafStem { facing: HorizontalDirection, waterlogged: bool },
    SmallDripleaf { facing: HorizontalDirection, half: DoubleBlockHalf, waterlogged: bool },
    HangingRoots { waterlogged: bool },
    RootedDirt,
    Deepslate { axis: Axis },
    CobbledDeepslate,
    CobbledDeepslateStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    CobbledDeepslateSlab { r#type: SlabType, waterlogged: bool },
    CobbledDeepslateWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    PolishedDeepslate,
    PolishedDeepslateStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    PolishedDeepslateSlab { r#type: SlabType, waterlogged: bool },
    PolishedDeepslateWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    DeepslateTiles,
    DeepslateTileStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    DeepslateTileSlab { r#type: SlabType, waterlogged: bool },
    DeepslateTileWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    DeepslateBricks,
    DeepslateBrickStairs { facing: HorizontalDirection, half: BlockHalf, shape: StairShape, waterlogged: bool },
    DeepslateBrickSlab { r#type: SlabType, waterlogged: bool },
    DeepslateBrickWall { east: WallShape, north: WallShape, south: WallShape, up: bool, waterlogged: bool, west: WallShape },
    ChiseledDeepslate,
    CrackedDeepslateBricks,
    CrackedDeepslateTiles,
    InfestedDeepslate { axis: Axis },
    SmoothBasalt,
    RawIronBlock,
    RawCopperBlock,
    RawGoldBlock,
    PottedAzaleaBush,
    PottedFloweringAzaleaBush,
    Other { name: Cow<'a, str>, properties: Option<HashMap<Cow<'a, str>, Cow<'a, str>>> },
}
