use std::str::FromStr;

use crate::schema;
use super::{types::*, list::BlockState};

macro_rules! try_make {
    ($block:ident, $state:ident; $($name:ident => $type:ty),+) => {
        match $state.properties.as_ref() {
            Some(props) => Self::$block {
                $(
                    $name: match props.get(stringify!($name)) {
                        Some(val) => match <$type>::from_str(val).ok() {
                            Some(val) => val,
                            None => return Self::Other { name: $state.name.to_owned(), properties: $state.properties.to_owned() },
                        },
                        None => return Self::Other { name: $state.name.to_owned(), properties: $state.properties.to_owned() },
                    }
                ),+
            },
            None => Self::Other { name: $state.name.to_owned(), properties: $state.properties.to_owned() },
        }
    };
}

impl <'a> From<&schema::BlockState<'a>> for BlockState<'a> {
    fn from(state: &schema::BlockState<'a>) -> Self {
        match state.name.as_ref() {
            "minecraft:air" => Self::Air,
            "minecraft:stone" => Self::Stone,
            "minecraft:granite" => Self::Granite,
            "minecraft:polished_granite" => Self::PolishedGranite,
            "minecraft:diorite" => Self::Diorite,
            "minecraft:polished_diorite" => Self::PolishedDiorite,
            "minecraft:andesite" => Self::Andesite,
            "minecraft:polished_andesite" => Self::PolishedAndesite,
            "minecraft:grass_block" => try_make!(GrassBlock, state; snowy => bool),
            "minecraft:dirt" => Self::Dirt,
            "minecraft:coarse_dirt" => Self::CoarseDirt,
            "minecraft:podzol" => try_make!(Podzol, state; snowy => bool),
            "minecraft:cobblestone" => Self::Cobblestone,
            "minecraft:oak_planks" => Self::OakPlanks,
            "minecraft:spruce_planks" => Self::SprucePlanks,
            "minecraft:birch_planks" => Self::BirchPlanks,
            "minecraft:jungle_planks" => Self::JunglePlanks,
            "minecraft:acacia_planks" => Self::AcaciaPlanks,
            "minecraft:dark_oak_planks" => Self::DarkOakPlanks,
            "minecraft:oak_sapling" => try_make!(OakSapling, state; stage => u8),
            "minecraft:spruce_sapling" => try_make!(SpruceSapling, state; stage => u8),
            "minecraft:birch_sapling" => try_make!(BirchSapling, state; stage => u8),
            "minecraft:jungle_sapling" => try_make!(JungleSapling, state; stage => u8),
            "minecraft:acacia_sapling" => try_make!(AcaciaSapling, state; stage => u8),
            "minecraft:dark_oak_sapling" => try_make!(DarkOakSapling, state; stage => u8),
            "minecraft:bedrock" => Self::Bedrock,
            "minecraft:water" => try_make!(Water, state; level => u8),
            "minecraft:lava" => try_make!(Lava, state; level => u8),
            "minecraft:sand" => Self::Sand,
            "minecraft:red_sand" => Self::RedSand,
            "minecraft:gravel" => Self::Gravel,
            "minecraft:gold_ore" => Self::GoldOre,
            "minecraft:deepslate_gold_ore" => Self::DeepslateGoldOre,
            "minecraft:iron_ore" => Self::IronOre,
            "minecraft:deepslate_iron_ore" => Self::DeepslateIronOre,
            "minecraft:coal_ore" => Self::CoalOre,
            "minecraft:deepslate_coal_ore" => Self::DeepslateCoalOre,
            "minecraft:nether_gold_ore" => Self::NetherGoldOre,
            "minecraft:oak_log" => try_make!(OakLog, state; axis => Axis),
            "minecraft:spruce_log" => try_make!(SpruceLog, state; axis => Axis),
            "minecraft:birch_log" => try_make!(BirchLog, state; axis => Axis),
            "minecraft:jungle_log" => try_make!(JungleLog, state; axis => Axis),
            "minecraft:acacia_log" => try_make!(AcaciaLog, state; axis => Axis),
            "minecraft:dark_oak_log" => try_make!(DarkOakLog, state; axis => Axis),
            "minecraft:stripped_spruce_log" => try_make!(StrippedSpruceLog, state; axis => Axis),
            "minecraft:stripped_birch_log" => try_make!(StrippedBirchLog, state; axis => Axis),
            "minecraft:stripped_jungle_log" => try_make!(StrippedJungleLog, state; axis => Axis),
            "minecraft:stripped_acacia_log" => try_make!(StrippedAcaciaLog, state; axis => Axis),
            "minecraft:stripped_dark_oak_log" => try_make!(StrippedDarkOakLog, state; axis => Axis),
            "minecraft:stripped_oak_log" => try_make!(StrippedOakLog, state; axis => Axis),
            "minecraft:oak_wood" => try_make!(OakWood, state; axis => Axis),
            "minecraft:spruce_wood" => try_make!(SpruceWood, state; axis => Axis),
            "minecraft:birch_wood" => try_make!(BirchWood, state; axis => Axis),
            "minecraft:jungle_wood" => try_make!(JungleWood, state; axis => Axis),
            "minecraft:acacia_wood" => try_make!(AcaciaWood, state; axis => Axis),
            "minecraft:dark_oak_wood" => try_make!(DarkOakWood, state; axis => Axis),
            "minecraft:stripped_oak_wood" => try_make!(StrippedOakWood, state; axis => Axis),
            "minecraft:stripped_spruce_wood" => try_make!(StrippedSpruceWood, state; axis => Axis),
            "minecraft:stripped_birch_wood" => try_make!(StrippedBirchWood, state; axis => Axis),
            "minecraft:stripped_jungle_wood" => try_make!(StrippedJungleWood, state; axis => Axis),
            "minecraft:stripped_acacia_wood" => try_make!(StrippedAcaciaWood, state; axis => Axis),
            "minecraft:stripped_dark_oak_wood" => try_make!(StrippedDarkOakWood, state; axis => Axis),
            "minecraft:oak_leaves" => try_make!(OakLeaves, state; distance => u8, persistent => bool),
            "minecraft:spruce_leaves" => try_make!(SpruceLeaves, state; distance => u8, persistent => bool),
            "minecraft:birch_leaves" => try_make!(BirchLeaves, state; distance => u8, persistent => bool),
            "minecraft:jungle_leaves" => try_make!(JungleLeaves, state; distance => u8, persistent => bool),
            "minecraft:acacia_leaves" => try_make!(AcaciaLeaves, state; distance => u8, persistent => bool),
            "minecraft:dark_oak_leaves" => try_make!(DarkOakLeaves, state; distance => u8, persistent => bool),
            "minecraft:azalea_leaves" => try_make!(AzaleaLeaves, state; distance => u8, persistent => bool),
            "minecraft:flowering_azalea_leaves" => try_make!(FloweringAzaleaLeaves, state; distance => u8, persistent => bool),
            "minecraft:sponge" => Self::Sponge,
            "minecraft:wet_sponge" => Self::WetSponge,
            "minecraft:glass" => Self::Glass,
            "minecraft:lapis_ore" => Self::LapisOre,
            "minecraft:deepslate_lapis_ore" => Self::DeepslateLapisOre,
            "minecraft:lapis_block" => Self::LapisBlock,
            "minecraft:dispenser" => try_make!(Dispenser, state; facing => Direction, triggered => bool),
            "minecraft:sandstone" => Self::Sandstone,
            "minecraft:chiseled_sandstone" => Self::ChiseledSandstone,
            "minecraft:cut_sandstone" => Self::CutSandstone,
            "minecraft:note_block" => try_make!(NoteBlock, state; instrument => Instrument, note => u8, powered => bool),
            "minecraft:white_bed" => try_make!(WhiteBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:orange_bed" => try_make!(OrangeBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:magenta_bed" => try_make!(MagentaBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:light_blue_bed" => try_make!(LightBlueBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:yellow_bed" => try_make!(YellowBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:lime_bed" => try_make!(LimeBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:pink_bed" => try_make!(PinkBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:gray_bed" => try_make!(GrayBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:light_gray_bed" => try_make!(LightGrayBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:cyan_bed" => try_make!(CyanBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:purple_bed" => try_make!(PurpleBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:blue_bed" => try_make!(BlueBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:brown_bed" => try_make!(BrownBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:green_bed" => try_make!(GreenBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:red_bed" => try_make!(RedBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:black_bed" => try_make!(BlackBed, state; facing => HorizontalDirection, occupied => bool, part => BedPart),
            "minecraft:powered_rail" => try_make!(PoweredRail, state; powered => bool, shape => RailShape, waterlogged => bool),
            "minecraft:detector_rail" => try_make!(DetectorRail, state; powered => bool, shape => RailShape, waterlogged => bool),
            "minecraft:sticky_piston" => try_make!(StickyPiston, state; extended => bool, facing => Direction),
            "minecraft:cobweb" => Self::Cobweb,
            "minecraft:grass" => Self::Grass,
            "minecraft:fern" => Self::Fern,
            "minecraft:dead_bush" => Self::DeadBush,
            "minecraft:seagrass" => Self::Seagrass,
            "minecraft:tall_seagrass" => try_make!(TallSeagrass, state; half => DoubleBlockHalf),
            "minecraft:piston" => try_make!(Piston, state; extended => bool, facing => Direction),
            "minecraft:piston_head" => try_make!(PistonHead, state; facing => Direction, short => bool, r#type => PistonType),
            "minecraft:white_wool" => Self::WhiteWool,
            "minecraft:orange_wool" => Self::OrangeWool,
            "minecraft:magenta_wool" => Self::MagentaWool,
            "minecraft:light_blue_wool" => Self::LightBlueWool,
            "minecraft:yellow_wool" => Self::YellowWool,
            "minecraft:lime_wool" => Self::LimeWool,
            "minecraft:pink_wool" => Self::PinkWool,
            "minecraft:gray_wool" => Self::GrayWool,
            "minecraft:light_gray_wool" => Self::LightGrayWool,
            "minecraft:cyan_wool" => Self::CyanWool,
            "minecraft:purple_wool" => Self::PurpleWool,
            "minecraft:blue_wool" => Self::BlueWool,
            "minecraft:brown_wool" => Self::BrownWool,
            "minecraft:green_wool" => Self::GreenWool,
            "minecraft:red_wool" => Self::RedWool,
            "minecraft:black_wool" => Self::BlackWool,
            "minecraft:moving_piston" => try_make!(MovingPiston, state; facing => Direction, r#type => PistonType),
            "minecraft:dandelion" => Self::Dandelion,
            "minecraft:poppy" => Self::Poppy,
            "minecraft:blue_orchid" => Self::BlueOrchid,
            "minecraft:allium" => Self::Allium,
            "minecraft:azure_bluet" => Self::AzureBluet,
            "minecraft:red_tulip" => Self::RedTulip,
            "minecraft:orange_tulip" => Self::OrangeTulip,
            "minecraft:white_tulip" => Self::WhiteTulip,
            "minecraft:pink_tulip" => Self::PinkTulip,
            "minecraft:oxeye_daisy" => Self::OxeyeDaisy,
            "minecraft:cornflower" => Self::Cornflower,
            "minecraft:wither_rose" => Self::WitherRose,
            "minecraft:lily_of_the_valley" => Self::LilyOfTheValley,
            "minecraft:brown_mushroom" => Self::BrownMushroom,
            "minecraft:red_mushroom" => Self::RedMushroom,
            "minecraft:gold_block" => Self::GoldBlock,
            "minecraft:iron_block" => Self::IronBlock,
            "minecraft:bricks" => Self::Bricks,
            "minecraft:tnt" => try_make!(Tnt, state; unstable => bool),
            "minecraft:bookshelf" => Self::Bookshelf,
            "minecraft:mossy_cobblestone" => Self::MossyCobblestone,
            "minecraft:obsidian" => Self::Obsidian,
            "minecraft:torch" => Self::Torch,
            "minecraft:wall_torch" => try_make!(WallTorch, state; facing => HorizontalDirection),
            "minecraft:fire" => try_make!(Fire, state; age => u8, east => bool, north => bool, south => bool, up => bool, west => bool),
            "minecraft:soul_fire" => Self::SoulFire,
            "minecraft:spawner" => Self::Spawner,
            "minecraft:oak_stairs" => try_make!(OakStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:chest" => try_make!(Chest, state; facing => HorizontalDirection, r#type => ChestType, waterlogged => bool),
            "minecraft:redstone_wire" => try_make!(RedstoneWire, state; east => WireConnection, north => WireConnection, power => u8, south => WireConnection, west => WireConnection),
            "minecraft:diamond_ore" => Self::DiamondOre,
            "minecraft:deepslate_diamond_ore" => Self::DeepslateDiamondOre,
            "minecraft:diamond_block" => Self::DiamondBlock,
            "minecraft:crafting_table" => Self::CraftingTable,
            "minecraft:wheat" => try_make!(Wheat, state; age => u8),
            "minecraft:farmland" => try_make!(Farmland, state; moisture => u8),
            "minecraft:furnace" => try_make!(Furnace, state; facing => HorizontalDirection, lit => bool),
            "minecraft:oak_sign" => try_make!(OakSign, state; rotation => u8, waterlogged => bool),
            "minecraft:spruce_sign" => try_make!(SpruceSign, state; rotation => u8, waterlogged => bool),
            "minecraft:birch_sign" => try_make!(BirchSign, state; rotation => u8, waterlogged => bool),
            "minecraft:acacia_sign" => try_make!(AcaciaSign, state; rotation => u8, waterlogged => bool),
            "minecraft:jungle_sign" => try_make!(JungleSign, state; rotation => u8, waterlogged => bool),
            "minecraft:dark_oak_sign" => try_make!(DarkOakSign, state; rotation => u8, waterlogged => bool),
            "minecraft:oak_door" => try_make!(OakDoor, state; facing => HorizontalDirection, half => DoubleBlockHalf, hinge => DoorHinge, open => bool, powered => bool),
            "minecraft:ladder" => try_make!(Ladder, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:rail" => try_make!(Rail, state; shape => RailShape, waterlogged => bool),
            "minecraft:cobblestone_stairs" => try_make!(CobblestoneStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:oak_wall_sign" => try_make!(OakWallSign, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:spruce_wall_sign" => try_make!(SpruceWallSign, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:birch_wall_sign" => try_make!(BirchWallSign, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:acacia_wall_sign" => try_make!(AcaciaWallSign, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:jungle_wall_sign" => try_make!(JungleWallSign, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:dark_oak_wall_sign" => try_make!(DarkOakWallSign, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:lever" => try_make!(Lever, state; face => WallMountLocation, facing => HorizontalDirection, powered => bool),
            "minecraft:stone_pressure_plate" => try_make!(StonePressurePlate, state; powered => bool),
            "minecraft:iron_door" => try_make!(IronDoor, state; facing => HorizontalDirection, half => DoubleBlockHalf, hinge => DoorHinge, open => bool, powered => bool),
            "minecraft:oak_pressure_plate" => try_make!(OakPressurePlate, state; powered => bool),
            "minecraft:spruce_pressure_plate" => try_make!(SprucePressurePlate, state; powered => bool),
            "minecraft:birch_pressure_plate" => try_make!(BirchPressurePlate, state; powered => bool),
            "minecraft:jungle_pressure_plate" => try_make!(JunglePressurePlate, state; powered => bool),
            "minecraft:acacia_pressure_plate" => try_make!(AcaciaPressurePlate, state; powered => bool),
            "minecraft:dark_oak_pressure_plate" => try_make!(DarkOakPressurePlate, state; powered => bool),
            "minecraft:redstone_ore" => try_make!(RedstoneOre, state; lit => bool),
            "minecraft:deepslate_redstone_ore" => try_make!(DeepslateRedstoneOre, state; lit => bool),
            "minecraft:redstone_torch" => try_make!(RedstoneTorch, state; lit => bool),
            "minecraft:redstone_wall_torch" => try_make!(RedstoneWallTorch, state; facing => HorizontalDirection, lit => bool),
            "minecraft:stone_button" => try_make!(StoneButton, state; face => WallMountLocation, facing => HorizontalDirection, powered => bool),
            "minecraft:snow" => try_make!(Snow, state; layers => u8),
            "minecraft:ice" => Self::Ice,
            "minecraft:snow_block" => Self::SnowBlock,
            "minecraft:cactus" => try_make!(Cactus, state; age => u8),
            "minecraft:clay" => Self::Clay,
            "minecraft:sugar_cane" => try_make!(SugarCane, state; age => u8),
            "minecraft:jukebox" => try_make!(Jukebox, state; has_record => bool),
            "minecraft:oak_fence" => try_make!(OakFence, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:pumpkin" => Self::Pumpkin,
            "minecraft:netherrack" => Self::Netherrack,
            "minecraft:soul_sand" => Self::SoulSand,
            "minecraft:soul_soil" => Self::SoulSoil,
            "minecraft:basalt" => try_make!(Basalt, state; axis => Axis),
            "minecraft:polished_basalt" => try_make!(PolishedBasalt, state; axis => Axis),
            "minecraft:soul_torch" => Self::SoulTorch,
            "minecraft:soul_wall_torch" => try_make!(SoulWallTorch, state; facing => HorizontalDirection),
            "minecraft:glowstone" => Self::Glowstone,
            "minecraft:nether_portal" => try_make!(NetherPortal, state; axis => HorizontalAxis),
            "minecraft:carved_pumpkin" => try_make!(CarvedPumpkin, state; facing => HorizontalDirection),
            "minecraft:jack_o_lantern" => try_make!(JackOLantern, state; facing => HorizontalDirection),
            "minecraft:cake" => try_make!(Cake, state; bites => u8),
            "minecraft:repeater" => try_make!(Repeater, state; delay => u8, facing => HorizontalDirection, locked => bool, powered => bool),
            "minecraft:white_stained_glass" => Self::WhiteStainedGlass,
            "minecraft:orange_stained_glass" => Self::OrangeStainedGlass,
            "minecraft:magenta_stained_glass" => Self::MagentaStainedGlass,
            "minecraft:light_blue_stained_glass" => Self::LightBlueStainedGlass,
            "minecraft:yellow_stained_glass" => Self::YellowStainedGlass,
            "minecraft:lime_stained_glass" => Self::LimeStainedGlass,
            "minecraft:pink_stained_glass" => Self::PinkStainedGlass,
            "minecraft:gray_stained_glass" => Self::GrayStainedGlass,
            "minecraft:light_gray_stained_glass" => Self::LightGrayStainedGlass,
            "minecraft:cyan_stained_glass" => Self::CyanStainedGlass,
            "minecraft:purple_stained_glass" => Self::PurpleStainedGlass,
            "minecraft:blue_stained_glass" => Self::BlueStainedGlass,
            "minecraft:brown_stained_glass" => Self::BrownStainedGlass,
            "minecraft:green_stained_glass" => Self::GreenStainedGlass,
            "minecraft:red_stained_glass" => Self::RedStainedGlass,
            "minecraft:black_stained_glass" => Self::BlackStainedGlass,
            "minecraft:oak_trapdoor" => try_make!(OakTrapdoor, state; facing => HorizontalDirection, half => BlockHalf, open => bool, powered => bool, waterlogged => bool),
            "minecraft:spruce_trapdoor" => try_make!(SpruceTrapdoor, state; facing => HorizontalDirection, half => BlockHalf, open => bool, powered => bool, waterlogged => bool),
            "minecraft:birch_trapdoor" => try_make!(BirchTrapdoor, state; facing => HorizontalDirection, half => BlockHalf, open => bool, powered => bool, waterlogged => bool),
            "minecraft:jungle_trapdoor" => try_make!(JungleTrapdoor, state; facing => HorizontalDirection, half => BlockHalf, open => bool, powered => bool, waterlogged => bool),
            "minecraft:acacia_trapdoor" => try_make!(AcaciaTrapdoor, state; facing => HorizontalDirection, half => BlockHalf, open => bool, powered => bool, waterlogged => bool),
            "minecraft:dark_oak_trapdoor" => try_make!(DarkOakTrapdoor, state; facing => HorizontalDirection, half => BlockHalf, open => bool, powered => bool, waterlogged => bool),
            "minecraft:stone_bricks" => Self::StoneBricks,
            "minecraft:mossy_stone_bricks" => Self::MossyStoneBricks,
            "minecraft:cracked_stone_bricks" => Self::CrackedStoneBricks,
            "minecraft:chiseled_stone_bricks" => Self::ChiseledStoneBricks,
            "minecraft:infested_stone" => Self::InfestedStone,
            "minecraft:infested_cobblestone" => Self::InfestedCobblestone,
            "minecraft:infested_stone_bricks" => Self::InfestedStoneBricks,
            "minecraft:infested_mossy_stone_bricks" => Self::InfestedMossyStoneBricks,
            "minecraft:infested_cracked_stone_bricks" => Self::InfestedCrackedStoneBricks,
            "minecraft:infested_chiseled_stone_bricks" => Self::InfestedChiseledStoneBricks,
            "minecraft:brown_mushroom_block" => try_make!(BrownMushroomBlock, state; down => bool, east => bool, north => bool, south => bool, up => bool, west => bool),
            "minecraft:red_mushroom_block" => try_make!(RedMushroomBlock, state; down => bool, east => bool, north => bool, south => bool, up => bool, west => bool),
            "minecraft:mushroom_stem" => try_make!(MushroomStem, state; down => bool, east => bool, north => bool, south => bool, up => bool, west => bool),
            "minecraft:iron_bars" => try_make!(IronBars, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:chain" => try_make!(Chain, state; axis => Axis, waterlogged => bool),
            "minecraft:glass_pane" => try_make!(GlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:melon" => Self::Melon,
            "minecraft:attached_pumpkin_stem" => try_make!(AttachedPumpkinStem, state; facing => HorizontalDirection),
            "minecraft:attached_melon_stem" => try_make!(AttachedMelonStem, state; facing => HorizontalDirection),
            "minecraft:pumpkin_stem" => try_make!(PumpkinStem, state; age => u8),
            "minecraft:melon_stem" => try_make!(MelonStem, state; age => u8),
            "minecraft:vine" => try_make!(Vine, state; east => bool, north => bool, south => bool, up => bool, west => bool),
            "minecraft:glow_lichen" => try_make!(GlowLichen, state; down => bool, east => bool, north => bool, south => bool, up => bool, waterlogged => bool, west => bool),
            "minecraft:oak_fence_gate" => try_make!(OakFenceGate, state; facing => HorizontalDirection, in_wall => bool, open => bool, powered => bool),
            "minecraft:brick_stairs" => try_make!(BrickStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:stone_brick_stairs" => try_make!(StoneBrickStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:mycelium" => try_make!(Mycelium, state; snowy => bool),
            "minecraft:lily_pad" => Self::LilyPad,
            "minecraft:nether_bricks" => Self::NetherBricks,
            "minecraft:nether_brick_fence" => try_make!(NetherBrickFence, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:nether_brick_stairs" => try_make!(NetherBrickStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:nether_wart" => try_make!(NetherWart, state; age => u8),
            "minecraft:enchanting_table" => Self::EnchantingTable,
            "minecraft:brewing_stand" => try_make!(BrewingStand, state; has_bottle_0 => bool, has_bottle_1 => bool, has_bottle_2 => bool),
            "minecraft:cauldron" => Self::Cauldron,
            "minecraft:water_cauldron" => try_make!(WaterCauldron, state; level => u8),
            "minecraft:lava_cauldron" => Self::LavaCauldron,
            "minecraft:powder_snow_cauldron" => try_make!(PowderSnowCauldron, state; level => u8),
            "minecraft:end_portal" => Self::EndPortal,
            "minecraft:end_portal_frame" => try_make!(EndPortalFrame, state; eye => bool, facing => HorizontalDirection),
            "minecraft:end_stone" => Self::EndStone,
            "minecraft:dragon_egg" => Self::DragonEgg,
            "minecraft:redstone_lamp" => try_make!(RedstoneLamp, state; lit => bool),
            "minecraft:cocoa" => try_make!(Cocoa, state; age => u8, facing => HorizontalDirection),
            "minecraft:sandstone_stairs" => try_make!(SandstoneStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:emerald_ore" => Self::EmeraldOre,
            "minecraft:deepslate_emerald_ore" => Self::DeepslateEmeraldOre,
            "minecraft:ender_chest" => try_make!(EnderChest, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:tripwire_hook" => try_make!(TripwireHook, state; attached => bool, facing => HorizontalDirection, powered => bool),
            "minecraft:tripwire" => try_make!(Tripwire, state; attached => bool, disarmed => bool, east => bool, north => bool, powered => bool, south => bool, west => bool),
            "minecraft:emerald_block" => Self::EmeraldBlock,
            "minecraft:spruce_stairs" => try_make!(SpruceStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:birch_stairs" => try_make!(BirchStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:jungle_stairs" => try_make!(JungleStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:command_block" => try_make!(CommandBlock, state; conditional => bool, facing => Direction),
            "minecraft:beacon" => Self::Beacon,
            "minecraft:cobblestone_wall" => try_make!(CobblestoneWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:mossy_cobblestone_wall" => try_make!(MossyCobblestoneWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:flower_pot" => Self::FlowerPot,
            "minecraft:potted_oak_sapling" => Self::PottedOakSapling,
            "minecraft:potted_spruce_sapling" => Self::PottedSpruceSapling,
            "minecraft:potted_birch_sapling" => Self::PottedBirchSapling,
            "minecraft:potted_jungle_sapling" => Self::PottedJungleSapling,
            "minecraft:potted_acacia_sapling" => Self::PottedAcaciaSapling,
            "minecraft:potted_dark_oak_sapling" => Self::PottedDarkOakSapling,
            "minecraft:potted_fern" => Self::PottedFern,
            "minecraft:potted_dandelion" => Self::PottedDandelion,
            "minecraft:potted_poppy" => Self::PottedPoppy,
            "minecraft:potted_blue_orchid" => Self::PottedBlueOrchid,
            "minecraft:potted_allium" => Self::PottedAllium,
            "minecraft:potted_azure_bluet" => Self::PottedAzureBluet,
            "minecraft:potted_red_tulip" => Self::PottedRedTulip,
            "minecraft:potted_orange_tulip" => Self::PottedOrangeTulip,
            "minecraft:potted_white_tulip" => Self::PottedWhiteTulip,
            "minecraft:potted_pink_tulip" => Self::PottedPinkTulip,
            "minecraft:potted_oxeye_daisy" => Self::PottedOxeyeDaisy,
            "minecraft:potted_cornflower" => Self::PottedCornflower,
            "minecraft:potted_lily_of_the_valley" => Self::PottedLilyOfTheValley,
            "minecraft:potted_wither_rose" => Self::PottedWitherRose,
            "minecraft:potted_red_mushroom" => Self::PottedRedMushroom,
            "minecraft:potted_brown_mushroom" => Self::PottedBrownMushroom,
            "minecraft:potted_dead_bush" => Self::PottedDeadBush,
            "minecraft:potted_cactus" => Self::PottedCactus,
            "minecraft:carrots" => try_make!(Carrots, state; age => u8),
            "minecraft:potatoes" => try_make!(Potatoes, state; age => u8),
            "minecraft:oak_button" => try_make!(OakButton, state; face => WallMountLocation, facing => HorizontalDirection, powered => bool),
            "minecraft:spruce_button" => try_make!(SpruceButton, state; face => WallMountLocation, facing => HorizontalDirection, powered => bool),
            "minecraft:birch_button" => try_make!(BirchButton, state; face => WallMountLocation, facing => HorizontalDirection, powered => bool),
            "minecraft:jungle_button" => try_make!(JungleButton, state; face => WallMountLocation, facing => HorizontalDirection, powered => bool),
            "minecraft:acacia_button" => try_make!(AcaciaButton, state; face => WallMountLocation, facing => HorizontalDirection, powered => bool),
            "minecraft:dark_oak_button" => try_make!(DarkOakButton, state; face => WallMountLocation, facing => HorizontalDirection, powered => bool),
            "minecraft:skeleton_skull" => try_make!(SkeletonSkull, state; rotation => u8),
            "minecraft:skeleton_wall_skull" => try_make!(SkeletonWallSkull, state; facing => HorizontalDirection),
            "minecraft:wither_skeleton_skull" => try_make!(WitherSkeletonSkull, state; rotation => u8),
            "minecraft:wither_skeleton_wall_skull" => try_make!(WitherSkeletonWallSkull, state; facing => HorizontalDirection),
            "minecraft:zombie_head" => try_make!(ZombieHead, state; rotation => u8),
            "minecraft:zombie_wall_head" => try_make!(ZombieWallHead, state; facing => HorizontalDirection),
            "minecraft:player_head" => try_make!(PlayerHead, state; rotation => u8),
            "minecraft:player_wall_head" => try_make!(PlayerWallHead, state; facing => HorizontalDirection),
            "minecraft:creeper_head" => try_make!(CreeperHead, state; rotation => u8),
            "minecraft:creeper_wall_head" => try_make!(CreeperWallHead, state; facing => HorizontalDirection),
            "minecraft:dragon_head" => try_make!(DragonHead, state; rotation => u8),
            "minecraft:dragon_wall_head" => try_make!(DragonWallHead, state; facing => HorizontalDirection),
            "minecraft:anvil" => try_make!(Anvil, state; facing => HorizontalDirection),
            "minecraft:chipped_anvil" => try_make!(ChippedAnvil, state; facing => HorizontalDirection),
            "minecraft:damaged_anvil" => try_make!(DamagedAnvil, state; facing => HorizontalDirection),
            "minecraft:trapped_chest" => try_make!(TrappedChest, state; facing => HorizontalDirection, r#type => ChestType, waterlogged => bool),
            "minecraft:light_weighted_pressure_plate" => try_make!(LightWeightedPressurePlate, state; power => u8),
            "minecraft:heavy_weighted_pressure_plate" => try_make!(HeavyWeightedPressurePlate, state; power => u8),
            "minecraft:comparator" => try_make!(Comparator, state; facing => HorizontalDirection, mode => ComparatorMode, powered => bool),
            "minecraft:daylight_detector" => try_make!(DaylightDetector, state; inverted => bool, power => u8),
            "minecraft:redstone_block" => Self::RedstoneBlock,
            "minecraft:nether_quartz_ore" => Self::NetherQuartzOre,
            "minecraft:hopper" => try_make!(Hopper, state; enabled => bool, facing => HopperDirection),
            "minecraft:quartz_block" => Self::QuartzBlock,
            "minecraft:chiseled_quartz_block" => Self::ChiseledQuartzBlock,
            "minecraft:quartz_pillar" => try_make!(QuartzPillar, state; axis => Axis),
            "minecraft:quartz_stairs" => try_make!(QuartzStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:activator_rail" => try_make!(ActivatorRail, state; powered => bool, shape => RailShape, waterlogged => bool),
            "minecraft:dropper" => try_make!(Dropper, state; facing => Direction, triggered => bool),
            "minecraft:white_terracotta" => Self::WhiteTerracotta,
            "minecraft:orange_terracotta" => Self::OrangeTerracotta,
            "minecraft:magenta_terracotta" => Self::MagentaTerracotta,
            "minecraft:light_blue_terracotta" => Self::LightBlueTerracotta,
            "minecraft:yellow_terracotta" => Self::YellowTerracotta,
            "minecraft:lime_terracotta" => Self::LimeTerracotta,
            "minecraft:pink_terracotta" => Self::PinkTerracotta,
            "minecraft:gray_terracotta" => Self::GrayTerracotta,
            "minecraft:light_gray_terracotta" => Self::LightGrayTerracotta,
            "minecraft:cyan_terracotta" => Self::CyanTerracotta,
            "minecraft:purple_terracotta" => Self::PurpleTerracotta,
            "minecraft:blue_terracotta" => Self::BlueTerracotta,
            "minecraft:brown_terracotta" => Self::BrownTerracotta,
            "minecraft:green_terracotta" => Self::GreenTerracotta,
            "minecraft:red_terracotta" => Self::RedTerracotta,
            "minecraft:black_terracotta" => Self::BlackTerracotta,
            "minecraft:white_stained_glass_pane" => try_make!(WhiteStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:orange_stained_glass_pane" => try_make!(OrangeStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:magenta_stained_glass_pane" => try_make!(MagentaStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:light_blue_stained_glass_pane" => try_make!(LightBlueStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:yellow_stained_glass_pane" => try_make!(YellowStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:lime_stained_glass_pane" => try_make!(LimeStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:pink_stained_glass_pane" => try_make!(PinkStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:gray_stained_glass_pane" => try_make!(GrayStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:light_gray_stained_glass_pane" => try_make!(LightGrayStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:cyan_stained_glass_pane" => try_make!(CyanStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:purple_stained_glass_pane" => try_make!(PurpleStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:blue_stained_glass_pane" => try_make!(BlueStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:brown_stained_glass_pane" => try_make!(BrownStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:green_stained_glass_pane" => try_make!(GreenStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:red_stained_glass_pane" => try_make!(RedStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:black_stained_glass_pane" => try_make!(BlackStainedGlassPane, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:acacia_stairs" => try_make!(AcaciaStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:dark_oak_stairs" => try_make!(DarkOakStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:slime_block" => Self::SlimeBlock,
            "minecraft:barrier" => Self::Barrier,
            "minecraft:light" => try_make!(Light, state; level => u8, waterlogged => bool),
            "minecraft:iron_trapdoor" => try_make!(IronTrapdoor, state; facing => HorizontalDirection, half => BlockHalf, open => bool, powered => bool, waterlogged => bool),
            "minecraft:prismarine" => Self::Prismarine,
            "minecraft:prismarine_bricks" => Self::PrismarineBricks,
            "minecraft:dark_prismarine" => Self::DarkPrismarine,
            "minecraft:prismarine_stairs" => try_make!(PrismarineStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:prismarine_brick_stairs" => try_make!(PrismarineBrickStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:dark_prismarine_stairs" => try_make!(DarkPrismarineStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:prismarine_slab" => try_make!(PrismarineSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:prismarine_brick_slab" => try_make!(PrismarineBrickSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:dark_prismarine_slab" => try_make!(DarkPrismarineSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:sea_lantern" => Self::SeaLantern,
            "minecraft:hay_block" => try_make!(HayBlock, state; axis => Axis),
            "minecraft:white_carpet" => Self::WhiteCarpet,
            "minecraft:orange_carpet" => Self::OrangeCarpet,
            "minecraft:magenta_carpet" => Self::MagentaCarpet,
            "minecraft:light_blue_carpet" => Self::LightBlueCarpet,
            "minecraft:yellow_carpet" => Self::YellowCarpet,
            "minecraft:lime_carpet" => Self::LimeCarpet,
            "minecraft:pink_carpet" => Self::PinkCarpet,
            "minecraft:gray_carpet" => Self::GrayCarpet,
            "minecraft:light_gray_carpet" => Self::LightGrayCarpet,
            "minecraft:cyan_carpet" => Self::CyanCarpet,
            "minecraft:purple_carpet" => Self::PurpleCarpet,
            "minecraft:blue_carpet" => Self::BlueCarpet,
            "minecraft:brown_carpet" => Self::BrownCarpet,
            "minecraft:green_carpet" => Self::GreenCarpet,
            "minecraft:red_carpet" => Self::RedCarpet,
            "minecraft:black_carpet" => Self::BlackCarpet,
            "minecraft:terracotta" => Self::Terracotta,
            "minecraft:coal_block" => Self::CoalBlock,
            "minecraft:packed_ice" => Self::PackedIce,
            "minecraft:sunflower" => try_make!(Sunflower, state; half => DoubleBlockHalf),
            "minecraft:lilac" => try_make!(Lilac, state; half => DoubleBlockHalf),
            "minecraft:rose_bush" => try_make!(RoseBush, state; half => DoubleBlockHalf),
            "minecraft:peony" => try_make!(Peony, state; half => DoubleBlockHalf),
            "minecraft:tall_grass" => try_make!(TallGrass, state; half => DoubleBlockHalf),
            "minecraft:large_fern" => try_make!(LargeFern, state; half => DoubleBlockHalf),
            "minecraft:white_banner" => try_make!(WhiteBanner, state; rotation => u8),
            "minecraft:orange_banner" => try_make!(OrangeBanner, state; rotation => u8),
            "minecraft:magenta_banner" => try_make!(MagentaBanner, state; rotation => u8),
            "minecraft:light_blue_banner" => try_make!(LightBlueBanner, state; rotation => u8),
            "minecraft:yellow_banner" => try_make!(YellowBanner, state; rotation => u8),
            "minecraft:lime_banner" => try_make!(LimeBanner, state; rotation => u8),
            "minecraft:pink_banner" => try_make!(PinkBanner, state; rotation => u8),
            "minecraft:gray_banner" => try_make!(GrayBanner, state; rotation => u8),
            "minecraft:light_gray_banner" => try_make!(LightGrayBanner, state; rotation => u8),
            "minecraft:cyan_banner" => try_make!(CyanBanner, state; rotation => u8),
            "minecraft:purple_banner" => try_make!(PurpleBanner, state; rotation => u8),
            "minecraft:blue_banner" => try_make!(BlueBanner, state; rotation => u8),
            "minecraft:brown_banner" => try_make!(BrownBanner, state; rotation => u8),
            "minecraft:green_banner" => try_make!(GreenBanner, state; rotation => u8),
            "minecraft:red_banner" => try_make!(RedBanner, state; rotation => u8),
            "minecraft:black_banner" => try_make!(BlackBanner, state; rotation => u8),
            "minecraft:white_wall_banner" => try_make!(WhiteWallBanner, state; facing => HorizontalDirection),
            "minecraft:orange_wall_banner" => try_make!(OrangeWallBanner, state; facing => HorizontalDirection),
            "minecraft:magenta_wall_banner" => try_make!(MagentaWallBanner, state; facing => HorizontalDirection),
            "minecraft:light_blue_wall_banner" => try_make!(LightBlueWallBanner, state; facing => HorizontalDirection),
            "minecraft:yellow_wall_banner" => try_make!(YellowWallBanner, state; facing => HorizontalDirection),
            "minecraft:lime_wall_banner" => try_make!(LimeWallBanner, state; facing => HorizontalDirection),
            "minecraft:pink_wall_banner" => try_make!(PinkWallBanner, state; facing => HorizontalDirection),
            "minecraft:gray_wall_banner" => try_make!(GrayWallBanner, state; facing => HorizontalDirection),
            "minecraft:light_gray_wall_banner" => try_make!(LightGrayWallBanner, state; facing => HorizontalDirection),
            "minecraft:cyan_wall_banner" => try_make!(CyanWallBanner, state; facing => HorizontalDirection),
            "minecraft:purple_wall_banner" => try_make!(PurpleWallBanner, state; facing => HorizontalDirection),
            "minecraft:blue_wall_banner" => try_make!(BlueWallBanner, state; facing => HorizontalDirection),
            "minecraft:brown_wall_banner" => try_make!(BrownWallBanner, state; facing => HorizontalDirection),
            "minecraft:green_wall_banner" => try_make!(GreenWallBanner, state; facing => HorizontalDirection),
            "minecraft:red_wall_banner" => try_make!(RedWallBanner, state; facing => HorizontalDirection),
            "minecraft:black_wall_banner" => try_make!(BlackWallBanner, state; facing => HorizontalDirection),
            "minecraft:red_sandstone" => Self::RedSandstone,
            "minecraft:chiseled_red_sandstone" => Self::ChiseledRedSandstone,
            "minecraft:cut_red_sandstone" => Self::CutRedSandstone,
            "minecraft:red_sandstone_stairs" => try_make!(RedSandstoneStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:oak_slab" => try_make!(OakSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:spruce_slab" => try_make!(SpruceSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:birch_slab" => try_make!(BirchSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:jungle_slab" => try_make!(JungleSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:acacia_slab" => try_make!(AcaciaSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:dark_oak_slab" => try_make!(DarkOakSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:stone_slab" => try_make!(StoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:smooth_stone_slab" => try_make!(SmoothStoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:sandstone_slab" => try_make!(SandstoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:cut_sandstone_slab" => try_make!(CutSandstoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:petrified_oak_slab" => try_make!(PetrifiedOakSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:cobblestone_slab" => try_make!(CobblestoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:brick_slab" => try_make!(BrickSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:stone_brick_slab" => try_make!(StoneBrickSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:nether_brick_slab" => try_make!(NetherBrickSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:quartz_slab" => try_make!(QuartzSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:red_sandstone_slab" => try_make!(RedSandstoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:cut_red_sandstone_slab" => try_make!(CutRedSandstoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:purpur_slab" => try_make!(PurpurSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:smooth_stone" => Self::SmoothStone,
            "minecraft:smooth_sandstone" => Self::SmoothSandstone,
            "minecraft:smooth_quartz" => Self::SmoothQuartz,
            "minecraft:smooth_red_sandstone" => Self::SmoothRedSandstone,
            "minecraft:spruce_fence_gate" => try_make!(SpruceFenceGate, state; facing => HorizontalDirection, in_wall => bool, open => bool, powered => bool),
            "minecraft:birch_fence_gate" => try_make!(BirchFenceGate, state; facing => HorizontalDirection, in_wall => bool, open => bool, powered => bool),
            "minecraft:jungle_fence_gate" => try_make!(JungleFenceGate, state; facing => HorizontalDirection, in_wall => bool, open => bool, powered => bool),
            "minecraft:acacia_fence_gate" => try_make!(AcaciaFenceGate, state; facing => HorizontalDirection, in_wall => bool, open => bool, powered => bool),
            "minecraft:dark_oak_fence_gate" => try_make!(DarkOakFenceGate, state; facing => HorizontalDirection, in_wall => bool, open => bool, powered => bool),
            "minecraft:spruce_fence" => try_make!(SpruceFence, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:birch_fence" => try_make!(BirchFence, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:jungle_fence" => try_make!(JungleFence, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:acacia_fence" => try_make!(AcaciaFence, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:dark_oak_fence" => try_make!(DarkOakFence, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:spruce_door" => try_make!(SpruceDoor, state; facing => HorizontalDirection, half => DoubleBlockHalf, hinge => DoorHinge, open => bool, powered => bool),
            "minecraft:birch_door" => try_make!(BirchDoor, state; facing => HorizontalDirection, half => DoubleBlockHalf, hinge => DoorHinge, open => bool, powered => bool),
            "minecraft:jungle_door" => try_make!(JungleDoor, state; facing => HorizontalDirection, half => DoubleBlockHalf, hinge => DoorHinge, open => bool, powered => bool),
            "minecraft:acacia_door" => try_make!(AcaciaDoor, state; facing => HorizontalDirection, half => DoubleBlockHalf, hinge => DoorHinge, open => bool, powered => bool),
            "minecraft:dark_oak_door" => try_make!(DarkOakDoor, state; facing => HorizontalDirection, half => DoubleBlockHalf, hinge => DoorHinge, open => bool, powered => bool),
            "minecraft:end_rod" => try_make!(EndRod, state; facing => Direction),
            "minecraft:chorus_plant" => try_make!(ChorusPlant, state; down => bool, east => bool, north => bool, south => bool, up => bool, west => bool),
            "minecraft:chorus_flower" => try_make!(ChorusFlower, state; age => u8),
            "minecraft:purpur_block" => Self::PurpurBlock,
            "minecraft:purpur_pillar" => try_make!(PurpurPillar, state; axis => Axis),
            "minecraft:purpur_stairs" => try_make!(PurpurStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:end_stone_bricks" => Self::EndStoneBricks,
            "minecraft:beetroots" => try_make!(Beetroots, state; age => u8),
            "minecraft:dirt_path" => Self::DirtPath,
            "minecraft:end_gateway" => Self::EndGateway,
            "minecraft:repeating_command_block" => try_make!(RepeatingCommandBlock, state; conditional => bool, facing => Direction),
            "minecraft:chain_command_block" => try_make!(ChainCommandBlock, state; conditional => bool, facing => Direction),
            "minecraft:frosted_ice" => try_make!(FrostedIce, state; age => u8),
            "minecraft:magma_block" => Self::MagmaBlock,
            "minecraft:nether_wart_block" => Self::NetherWartBlock,
            "minecraft:red_nether_bricks" => Self::RedNetherBricks,
            "minecraft:bone_block" => try_make!(BoneBlock, state; axis => Axis),
            "minecraft:structure_void" => Self::StructureVoid,
            "minecraft:observer" => try_make!(Observer, state; facing => Direction, powered => bool),
            "minecraft:shulker_box" => try_make!(ShulkerBox, state; facing => Direction),
            "minecraft:white_shulker_box" => try_make!(WhiteShulkerBox, state; facing => Direction),
            "minecraft:orange_shulker_box" => try_make!(OrangeShulkerBox, state; facing => Direction),
            "minecraft:magenta_shulker_box" => try_make!(MagentaShulkerBox, state; facing => Direction),
            "minecraft:light_blue_shulker_box" => try_make!(LightBlueShulkerBox, state; facing => Direction),
            "minecraft:yellow_shulker_box" => try_make!(YellowShulkerBox, state; facing => Direction),
            "minecraft:lime_shulker_box" => try_make!(LimeShulkerBox, state; facing => Direction),
            "minecraft:pink_shulker_box" => try_make!(PinkShulkerBox, state; facing => Direction),
            "minecraft:gray_shulker_box" => try_make!(GrayShulkerBox, state; facing => Direction),
            "minecraft:light_gray_shulker_box" => try_make!(LightGrayShulkerBox, state; facing => Direction),
            "minecraft:cyan_shulker_box" => try_make!(CyanShulkerBox, state; facing => Direction),
            "minecraft:purple_shulker_box" => try_make!(PurpleShulkerBox, state; facing => Direction),
            "minecraft:blue_shulker_box" => try_make!(BlueShulkerBox, state; facing => Direction),
            "minecraft:brown_shulker_box" => try_make!(BrownShulkerBox, state; facing => Direction),
            "minecraft:green_shulker_box" => try_make!(GreenShulkerBox, state; facing => Direction),
            "minecraft:red_shulker_box" => try_make!(RedShulkerBox, state; facing => Direction),
            "minecraft:black_shulker_box" => try_make!(BlackShulkerBox, state; facing => Direction),
            "minecraft:white_glazed_terracotta" => try_make!(WhiteGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:orange_glazed_terracotta" => try_make!(OrangeGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:magenta_glazed_terracotta" => try_make!(MagentaGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:light_blue_glazed_terracotta" => try_make!(LightBlueGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:yellow_glazed_terracotta" => try_make!(YellowGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:lime_glazed_terracotta" => try_make!(LimeGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:pink_glazed_terracotta" => try_make!(PinkGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:gray_glazed_terracotta" => try_make!(GrayGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:light_gray_glazed_terracotta" => try_make!(LightGrayGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:cyan_glazed_terracotta" => try_make!(CyanGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:purple_glazed_terracotta" => try_make!(PurpleGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:blue_glazed_terracotta" => try_make!(BlueGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:brown_glazed_terracotta" => try_make!(BrownGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:green_glazed_terracotta" => try_make!(GreenGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:red_glazed_terracotta" => try_make!(RedGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:black_glazed_terracotta" => try_make!(BlackGlazedTerracotta, state; facing => HorizontalDirection),
            "minecraft:white_concrete" => Self::WhiteConcrete,
            "minecraft:orange_concrete" => Self::OrangeConcrete,
            "minecraft:magenta_concrete" => Self::MagentaConcrete,
            "minecraft:light_blue_concrete" => Self::LightBlueConcrete,
            "minecraft:yellow_concrete" => Self::YellowConcrete,
            "minecraft:lime_concrete" => Self::LimeConcrete,
            "minecraft:pink_concrete" => Self::PinkConcrete,
            "minecraft:gray_concrete" => Self::GrayConcrete,
            "minecraft:light_gray_concrete" => Self::LightGrayConcrete,
            "minecraft:cyan_concrete" => Self::CyanConcrete,
            "minecraft:purple_concrete" => Self::PurpleConcrete,
            "minecraft:blue_concrete" => Self::BlueConcrete,
            "minecraft:brown_concrete" => Self::BrownConcrete,
            "minecraft:green_concrete" => Self::GreenConcrete,
            "minecraft:red_concrete" => Self::RedConcrete,
            "minecraft:black_concrete" => Self::BlackConcrete,
            "minecraft:white_concrete_powder" => Self::WhiteConcretePowder,
            "minecraft:orange_concrete_powder" => Self::OrangeConcretePowder,
            "minecraft:magenta_concrete_powder" => Self::MagentaConcretePowder,
            "minecraft:light_blue_concrete_powder" => Self::LightBlueConcretePowder,
            "minecraft:yellow_concrete_powder" => Self::YellowConcretePowder,
            "minecraft:lime_concrete_powder" => Self::LimeConcretePowder,
            "minecraft:pink_concrete_powder" => Self::PinkConcretePowder,
            "minecraft:gray_concrete_powder" => Self::GrayConcretePowder,
            "minecraft:light_gray_concrete_powder" => Self::LightGrayConcretePowder,
            "minecraft:cyan_concrete_powder" => Self::CyanConcretePowder,
            "minecraft:purple_concrete_powder" => Self::PurpleConcretePowder,
            "minecraft:blue_concrete_powder" => Self::BlueConcretePowder,
            "minecraft:brown_concrete_powder" => Self::BrownConcretePowder,
            "minecraft:green_concrete_powder" => Self::GreenConcretePowder,
            "minecraft:red_concrete_powder" => Self::RedConcretePowder,
            "minecraft:black_concrete_powder" => Self::BlackConcretePowder,
            "minecraft:kelp" => try_make!(Kelp, state; age => u8),
            "minecraft:kelp_plant" => Self::KelpPlant,
            "minecraft:dried_kelp_block" => Self::DriedKelpBlock,
            "minecraft:turtle_egg" => try_make!(TurtleEgg, state; eggs => u8, hatch => u8),
            "minecraft:dead_tube_coral_block" => Self::DeadTubeCoralBlock,
            "minecraft:dead_brain_coral_block" => Self::DeadBrainCoralBlock,
            "minecraft:dead_bubble_coral_block" => Self::DeadBubbleCoralBlock,
            "minecraft:dead_fire_coral_block" => Self::DeadFireCoralBlock,
            "minecraft:dead_horn_coral_block" => Self::DeadHornCoralBlock,
            "minecraft:tube_coral_block" => Self::TubeCoralBlock,
            "minecraft:brain_coral_block" => Self::BrainCoralBlock,
            "minecraft:bubble_coral_block" => Self::BubbleCoralBlock,
            "minecraft:fire_coral_block" => Self::FireCoralBlock,
            "minecraft:horn_coral_block" => Self::HornCoralBlock,
            "minecraft:dead_tube_coral" => try_make!(DeadTubeCoral, state; waterlogged => bool),
            "minecraft:dead_brain_coral" => try_make!(DeadBrainCoral, state; waterlogged => bool),
            "minecraft:dead_bubble_coral" => try_make!(DeadBubbleCoral, state; waterlogged => bool),
            "minecraft:dead_fire_coral" => try_make!(DeadFireCoral, state; waterlogged => bool),
            "minecraft:dead_horn_coral" => try_make!(DeadHornCoral, state; waterlogged => bool),
            "minecraft:tube_coral" => try_make!(TubeCoral, state; waterlogged => bool),
            "minecraft:brain_coral" => try_make!(BrainCoral, state; waterlogged => bool),
            "minecraft:bubble_coral" => try_make!(BubbleCoral, state; waterlogged => bool),
            "minecraft:fire_coral" => try_make!(FireCoral, state; waterlogged => bool),
            "minecraft:horn_coral" => try_make!(HornCoral, state; waterlogged => bool),
            "minecraft:dead_tube_coral_fan" => try_make!(DeadTubeCoralFan, state; waterlogged => bool),
            "minecraft:dead_brain_coral_fan" => try_make!(DeadBrainCoralFan, state; waterlogged => bool),
            "minecraft:dead_bubble_coral_fan" => try_make!(DeadBubbleCoralFan, state; waterlogged => bool),
            "minecraft:dead_fire_coral_fan" => try_make!(DeadFireCoralFan, state; waterlogged => bool),
            "minecraft:dead_horn_coral_fan" => try_make!(DeadHornCoralFan, state; waterlogged => bool),
            "minecraft:tube_coral_fan" => try_make!(TubeCoralFan, state; waterlogged => bool),
            "minecraft:brain_coral_fan" => try_make!(BrainCoralFan, state; waterlogged => bool),
            "minecraft:bubble_coral_fan" => try_make!(BubbleCoralFan, state; waterlogged => bool),
            "minecraft:fire_coral_fan" => try_make!(FireCoralFan, state; waterlogged => bool),
            "minecraft:horn_coral_fan" => try_make!(HornCoralFan, state; waterlogged => bool),
            "minecraft:dead_tube_coral_wall_fan" => try_make!(DeadTubeCoralWallFan, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:dead_brain_coral_wall_fan" => try_make!(DeadBrainCoralWallFan, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:dead_bubble_coral_wall_fan" => try_make!(DeadBubbleCoralWallFan, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:dead_fire_coral_wall_fan" => try_make!(DeadFireCoralWallFan, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:dead_horn_coral_wall_fan" => try_make!(DeadHornCoralWallFan, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:tube_coral_wall_fan" => try_make!(TubeCoralWallFan, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:brain_coral_wall_fan" => try_make!(BrainCoralWallFan, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:bubble_coral_wall_fan" => try_make!(BubbleCoralWallFan, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:fire_coral_wall_fan" => try_make!(FireCoralWallFan, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:horn_coral_wall_fan" => try_make!(HornCoralWallFan, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:sea_pickle" => try_make!(SeaPickle, state; pickles => u8, waterlogged => bool),
            "minecraft:blue_ice" => Self::BlueIce,
            "minecraft:conduit" => try_make!(Conduit, state; waterlogged => bool),
            "minecraft:bamboo_sapling" => Self::BambooSapling,
            "minecraft:bamboo" => try_make!(Bamboo, state; age => u8, leaves => BambooLeaves, stage => u8),
            "minecraft:potted_bamboo" => Self::PottedBamboo,
            "minecraft:void_air" => Self::VoidAir,
            "minecraft:cave_air" => Self::CaveAir,
            "minecraft:bubble_column" => try_make!(BubbleColumn, state; drag => bool),
            "minecraft:polished_granite_stairs" => try_make!(PolishedGraniteStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:smooth_red_sandstone_stairs" => try_make!(SmoothRedSandstoneStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:mossy_stone_brick_stairs" => try_make!(MossyStoneBrickStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:polished_diorite_stairs" => try_make!(PolishedDioriteStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:mossy_cobblestone_stairs" => try_make!(MossyCobblestoneStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:end_stone_brick_stairs" => try_make!(EndStoneBrickStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:stone_stairs" => try_make!(StoneStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:smooth_sandstone_stairs" => try_make!(SmoothSandstoneStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:smooth_quartz_stairs" => try_make!(SmoothQuartzStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:granite_stairs" => try_make!(GraniteStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:andesite_stairs" => try_make!(AndesiteStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:red_nether_brick_stairs" => try_make!(RedNetherBrickStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:polished_andesite_stairs" => try_make!(PolishedAndesiteStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:diorite_stairs" => try_make!(DioriteStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:polished_granite_slab" => try_make!(PolishedGraniteSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:smooth_red_sandstone_slab" => try_make!(SmoothRedSandstoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:mossy_stone_brick_slab" => try_make!(MossyStoneBrickSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:polished_diorite_slab" => try_make!(PolishedDioriteSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:mossy_cobblestone_slab" => try_make!(MossyCobblestoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:end_stone_brick_slab" => try_make!(EndStoneBrickSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:smooth_sandstone_slab" => try_make!(SmoothSandstoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:smooth_quartz_slab" => try_make!(SmoothQuartzSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:granite_slab" => try_make!(GraniteSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:andesite_slab" => try_make!(AndesiteSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:red_nether_brick_slab" => try_make!(RedNetherBrickSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:polished_andesite_slab" => try_make!(PolishedAndesiteSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:diorite_slab" => try_make!(DioriteSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:brick_wall" => try_make!(BrickWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:prismarine_wall" => try_make!(PrismarineWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:red_sandstone_wall" => try_make!(RedSandstoneWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:mossy_stone_brick_wall" => try_make!(MossyStoneBrickWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:granite_wall" => try_make!(GraniteWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:stone_brick_wall" => try_make!(StoneBrickWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:nether_brick_wall" => try_make!(NetherBrickWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:andesite_wall" => try_make!(AndesiteWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:red_nether_brick_wall" => try_make!(RedNetherBrickWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:sandstone_wall" => try_make!(SandstoneWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:end_stone_brick_wall" => try_make!(EndStoneBrickWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:diorite_wall" => try_make!(DioriteWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:scaffolding" => try_make!(Scaffolding, state; bottom => bool, distance => u8, waterlogged => bool),
            "minecraft:loom" => try_make!(Loom, state; facing => HorizontalDirection),
            "minecraft:barrel" => try_make!(Barrel, state; facing => Direction, open => bool),
            "minecraft:smoker" => try_make!(Smoker, state; facing => HorizontalDirection, lit => bool),
            "minecraft:blast_furnace" => try_make!(BlastFurnace, state; facing => HorizontalDirection, lit => bool),
            "minecraft:cartography_table" => Self::CartographyTable,
            "minecraft:fletching_table" => Self::FletchingTable,
            "minecraft:grindstone" => try_make!(Grindstone, state; face => WallMountLocation, facing => HorizontalDirection),
            "minecraft:lectern" => try_make!(Lectern, state; facing => HorizontalDirection, has_book => bool, powered => bool),
            "minecraft:smithing_table" => Self::SmithingTable,
            "minecraft:stonecutter" => try_make!(Stonecutter, state; facing => HorizontalDirection),
            "minecraft:bell" => try_make!(Bell, state; attachment => Attachment, facing => HorizontalDirection, powered => bool),
            "minecraft:lantern" => try_make!(Lantern, state; hanging => bool, waterlogged => bool),
            "minecraft:soul_lantern" => try_make!(SoulLantern, state; hanging => bool, waterlogged => bool),
            "minecraft:campfire" => try_make!(Campfire, state; facing => HorizontalDirection, lit => bool, signal_fire => bool, waterlogged => bool),
            "minecraft:soul_campfire" => try_make!(SoulCampfire, state; facing => HorizontalDirection, lit => bool, signal_fire => bool, waterlogged => bool),
            "minecraft:sweet_berry_bush" => try_make!(SweetBerryBush, state; age => u8),
            "minecraft:warped_stem" => try_make!(WarpedStem, state; axis => Axis),
            "minecraft:stripped_warped_stem" => try_make!(StrippedWarpedStem, state; axis => Axis),
            "minecraft:warped_hyphae" => try_make!(WarpedHyphae, state; axis => Axis),
            "minecraft:stripped_warped_hyphae" => try_make!(StrippedWarpedHyphae, state; axis => Axis),
            "minecraft:warped_nylium" => Self::WarpedNylium,
            "minecraft:warped_fungus" => Self::WarpedFungus,
            "minecraft:warped_wart_block" => Self::WarpedWartBlock,
            "minecraft:warped_roots" => Self::WarpedRoots,
            "minecraft:nether_sprouts" => Self::NetherSprouts,
            "minecraft:crimson_stem" => try_make!(CrimsonStem, state; axis => Axis),
            "minecraft:stripped_crimson_stem" => try_make!(StrippedCrimsonStem, state; axis => Axis),
            "minecraft:crimson_hyphae" => try_make!(CrimsonHyphae, state; axis => Axis),
            "minecraft:stripped_crimson_hyphae" => try_make!(StrippedCrimsonHyphae, state; axis => Axis),
            "minecraft:crimson_nylium" => Self::CrimsonNylium,
            "minecraft:crimson_fungus" => Self::CrimsonFungus,
            "minecraft:shroomlight" => Self::Shroomlight,
            "minecraft:weeping_vines" => try_make!(WeepingVines, state; age => u8),
            "minecraft:weeping_vines_plant" => Self::WeepingVinesPlant,
            "minecraft:twisting_vines" => try_make!(TwistingVines, state; age => u8),
            "minecraft:twisting_vines_plant" => Self::TwistingVinesPlant,
            "minecraft:crimson_roots" => Self::CrimsonRoots,
            "minecraft:crimson_planks" => Self::CrimsonPlanks,
            "minecraft:warped_planks" => Self::WarpedPlanks,
            "minecraft:crimson_slab" => try_make!(CrimsonSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:warped_slab" => try_make!(WarpedSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:crimson_pressure_plate" => try_make!(CrimsonPressurePlate, state; powered => bool),
            "minecraft:warped_pressure_plate" => try_make!(WarpedPressurePlate, state; powered => bool),
            "minecraft:crimson_fence" => try_make!(CrimsonFence, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:warped_fence" => try_make!(WarpedFence, state; east => bool, north => bool, south => bool, waterlogged => bool, west => bool),
            "minecraft:crimson_trapdoor" => try_make!(CrimsonTrapdoor, state; facing => HorizontalDirection, half => BlockHalf, open => bool, powered => bool, waterlogged => bool),
            "minecraft:warped_trapdoor" => try_make!(WarpedTrapdoor, state; facing => HorizontalDirection, half => BlockHalf, open => bool, powered => bool, waterlogged => bool),
            "minecraft:crimson_fence_gate" => try_make!(CrimsonFenceGate, state; facing => HorizontalDirection, in_wall => bool, open => bool, powered => bool),
            "minecraft:warped_fence_gate" => try_make!(WarpedFenceGate, state; facing => HorizontalDirection, in_wall => bool, open => bool, powered => bool),
            "minecraft:crimson_stairs" => try_make!(CrimsonStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:warped_stairs" => try_make!(WarpedStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:crimson_button" => try_make!(CrimsonButton, state; face => WallMountLocation, facing => HorizontalDirection, powered => bool),
            "minecraft:warped_button" => try_make!(WarpedButton, state; face => WallMountLocation, facing => HorizontalDirection, powered => bool),
            "minecraft:crimson_door" => try_make!(CrimsonDoor, state; facing => HorizontalDirection, half => DoubleBlockHalf, hinge => DoorHinge, open => bool, powered => bool),
            "minecraft:warped_door" => try_make!(WarpedDoor, state; facing => HorizontalDirection, half => DoubleBlockHalf, hinge => DoorHinge, open => bool, powered => bool),
            "minecraft:crimson_sign" => try_make!(CrimsonSign, state; rotation => u8, waterlogged => bool),
            "minecraft:warped_sign" => try_make!(WarpedSign, state; rotation => u8, waterlogged => bool),
            "minecraft:crimson_wall_sign" => try_make!(CrimsonWallSign, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:warped_wall_sign" => try_make!(WarpedWallSign, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:structure_block" => try_make!(StructureBlock, state; mode => StructureBlockMode),
            "minecraft:jigsaw" => try_make!(Jigsaw, state; orientation => Orientation),
            "minecraft:composter" => try_make!(Composter, state; level => u8),
            "minecraft:target" => try_make!(Target, state; power => u8),
            "minecraft:bee_nest" => try_make!(BeeNest, state; facing => HorizontalDirection, honey_level => u8),
            "minecraft:beehive" => try_make!(Beehive, state; facing => HorizontalDirection, honey_level => u8),
            "minecraft:honey_block" => Self::HoneyBlock,
            "minecraft:honeycomb_block" => Self::HoneycombBlock,
            "minecraft:netherite_block" => Self::NetheriteBlock,
            "minecraft:ancient_debris" => Self::AncientDebris,
            "minecraft:crying_obsidian" => Self::CryingObsidian,
            "minecraft:respawn_anchor" => try_make!(RespawnAnchor, state; charges => u8),
            "minecraft:potted_crimson_fungus" => Self::PottedCrimsonFungus,
            "minecraft:potted_warped_fungus" => Self::PottedWarpedFungus,
            "minecraft:potted_crimson_roots" => Self::PottedCrimsonRoots,
            "minecraft:potted_warped_roots" => Self::PottedWarpedRoots,
            "minecraft:lodestone" => Self::Lodestone,
            "minecraft:blackstone" => Self::Blackstone,
            "minecraft:blackstone_stairs" => try_make!(BlackstoneStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:blackstone_wall" => try_make!(BlackstoneWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:blackstone_slab" => try_make!(BlackstoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:polished_blackstone" => Self::PolishedBlackstone,
            "minecraft:polished_blackstone_bricks" => Self::PolishedBlackstoneBricks,
            "minecraft:cracked_polished_blackstone_bricks" => Self::CrackedPolishedBlackstoneBricks,
            "minecraft:chiseled_polished_blackstone" => Self::ChiseledPolishedBlackstone,
            "minecraft:polished_blackstone_brick_slab" => try_make!(PolishedBlackstoneBrickSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:polished_blackstone_brick_stairs" => try_make!(PolishedBlackstoneBrickStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:polished_blackstone_brick_wall" => try_make!(PolishedBlackstoneBrickWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:gilded_blackstone" => Self::GildedBlackstone,
            "minecraft:polished_blackstone_stairs" => try_make!(PolishedBlackstoneStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:polished_blackstone_slab" => try_make!(PolishedBlackstoneSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:polished_blackstone_pressure_plate" => try_make!(PolishedBlackstonePressurePlate, state; powered => bool),
            "minecraft:polished_blackstone_button" => try_make!(PolishedBlackstoneButton, state; face => WallMountLocation, facing => HorizontalDirection, powered => bool),
            "minecraft:polished_blackstone_wall" => try_make!(PolishedBlackstoneWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:chiseled_nether_bricks" => Self::ChiseledNetherBricks,
            "minecraft:cracked_nether_bricks" => Self::CrackedNetherBricks,
            "minecraft:quartz_bricks" => Self::QuartzBricks,
            "minecraft:candle" => try_make!(Candle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:white_candle" => try_make!(WhiteCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:orange_candle" => try_make!(OrangeCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:magenta_candle" => try_make!(MagentaCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:light_blue_candle" => try_make!(LightBlueCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:yellow_candle" => try_make!(YellowCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:lime_candle" => try_make!(LimeCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:pink_candle" => try_make!(PinkCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:gray_candle" => try_make!(GrayCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:light_gray_candle" => try_make!(LightGrayCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:cyan_candle" => try_make!(CyanCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:purple_candle" => try_make!(PurpleCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:blue_candle" => try_make!(BlueCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:brown_candle" => try_make!(BrownCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:green_candle" => try_make!(GreenCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:red_candle" => try_make!(RedCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:black_candle" => try_make!(BlackCandle, state; candles => u8, lit => bool, waterlogged => bool),
            "minecraft:candle_cake" => try_make!(CandleCake, state; lit => bool),
            "minecraft:white_candle_cake" => try_make!(WhiteCandleCake, state; lit => bool),
            "minecraft:orange_candle_cake" => try_make!(OrangeCandleCake, state; lit => bool),
            "minecraft:magenta_candle_cake" => try_make!(MagentaCandleCake, state; lit => bool),
            "minecraft:light_blue_candle_cake" => try_make!(LightBlueCandleCake, state; lit => bool),
            "minecraft:yellow_candle_cake" => try_make!(YellowCandleCake, state; lit => bool),
            "minecraft:lime_candle_cake" => try_make!(LimeCandleCake, state; lit => bool),
            "minecraft:pink_candle_cake" => try_make!(PinkCandleCake, state; lit => bool),
            "minecraft:gray_candle_cake" => try_make!(GrayCandleCake, state; lit => bool),
            "minecraft:light_gray_candle_cake" => try_make!(LightGrayCandleCake, state; lit => bool),
            "minecraft:cyan_candle_cake" => try_make!(CyanCandleCake, state; lit => bool),
            "minecraft:purple_candle_cake" => try_make!(PurpleCandleCake, state; lit => bool),
            "minecraft:blue_candle_cake" => try_make!(BlueCandleCake, state; lit => bool),
            "minecraft:brown_candle_cake" => try_make!(BrownCandleCake, state; lit => bool),
            "minecraft:green_candle_cake" => try_make!(GreenCandleCake, state; lit => bool),
            "minecraft:red_candle_cake" => try_make!(RedCandleCake, state; lit => bool),
            "minecraft:black_candle_cake" => try_make!(BlackCandleCake, state; lit => bool),
            "minecraft:amethyst_block" => Self::AmethystBlock,
            "minecraft:budding_amethyst" => Self::BuddingAmethyst,
            "minecraft:amethyst_cluster" => try_make!(AmethystCluster, state; facing => Direction, waterlogged => bool),
            "minecraft:large_amethyst_bud" => try_make!(LargeAmethystBud, state; facing => Direction, waterlogged => bool),
            "minecraft:medium_amethyst_bud" => try_make!(MediumAmethystBud, state; facing => Direction, waterlogged => bool),
            "minecraft:small_amethyst_bud" => try_make!(SmallAmethystBud, state; facing => Direction, waterlogged => bool),
            "minecraft:tuff" => Self::Tuff,
            "minecraft:calcite" => Self::Calcite,
            "minecraft:tinted_glass" => Self::TintedGlass,
            "minecraft:powder_snow" => Self::PowderSnow,
            "minecraft:sculk_sensor" => try_make!(SculkSensor, state; power => u8, sculk_sensor_phase => SculkSensorPhase, waterlogged => bool),
            "minecraft:oxidized_copper" => Self::OxidizedCopper,
            "minecraft:weathered_copper" => Self::WeatheredCopper,
            "minecraft:exposed_copper" => Self::ExposedCopper,
            "minecraft:copper_block" => Self::CopperBlock,
            "minecraft:copper_ore" => Self::CopperOre,
            "minecraft:deepslate_copper_ore" => Self::DeepslateCopperOre,
            "minecraft:oxidized_cut_copper" => Self::OxidizedCutCopper,
            "minecraft:weathered_cut_copper" => Self::WeatheredCutCopper,
            "minecraft:exposed_cut_copper" => Self::ExposedCutCopper,
            "minecraft:cut_copper" => Self::CutCopper,
            "minecraft:oxidized_cut_copper_stairs" => try_make!(OxidizedCutCopperStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:weathered_cut_copper_stairs" => try_make!(WeatheredCutCopperStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:exposed_cut_copper_stairs" => try_make!(ExposedCutCopperStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:cut_copper_stairs" => try_make!(CutCopperStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:oxidized_cut_copper_slab" => try_make!(OxidizedCutCopperSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:weathered_cut_copper_slab" => try_make!(WeatheredCutCopperSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:exposed_cut_copper_slab" => try_make!(ExposedCutCopperSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:cut_copper_slab" => try_make!(CutCopperSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:waxed_copper_block" => Self::WaxedCopperBlock,
            "minecraft:waxed_weathered_copper" => Self::WaxedWeatheredCopper,
            "minecraft:waxed_exposed_copper" => Self::WaxedExposedCopper,
            "minecraft:waxed_oxidized_copper" => Self::WaxedOxidizedCopper,
            "minecraft:waxed_oxidized_cut_copper" => Self::WaxedOxidizedCutCopper,
            "minecraft:waxed_weathered_cut_copper" => Self::WaxedWeatheredCutCopper,
            "minecraft:waxed_exposed_cut_copper" => Self::WaxedExposedCutCopper,
            "minecraft:waxed_cut_copper" => Self::WaxedCutCopper,
            "minecraft:waxed_oxidized_cut_copper_stairs" => try_make!(WaxedOxidizedCutCopperStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:waxed_weathered_cut_copper_stairs" => try_make!(WaxedWeatheredCutCopperStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:waxed_exposed_cut_copper_stairs" => try_make!(WaxedExposedCutCopperStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:waxed_cut_copper_stairs" => try_make!(WaxedCutCopperStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:waxed_oxidized_cut_copper_slab" => try_make!(WaxedOxidizedCutCopperSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:waxed_weathered_cut_copper_slab" => try_make!(WaxedWeatheredCutCopperSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:waxed_exposed_cut_copper_slab" => try_make!(WaxedExposedCutCopperSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:waxed_cut_copper_slab" => try_make!(WaxedCutCopperSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:lightning_rod" => try_make!(LightningRod, state; facing => Direction, powered => bool, waterlogged => bool),
            "minecraft:pointed_dripstone" => try_make!(PointedDripstone, state; thickness => Thickness, vertical_direction => VerticalDirection, waterlogged => bool),
            "minecraft:dripstone_block" => Self::DripstoneBlock,
            "minecraft:cave_vines" => try_make!(CaveVines, state; age => u8, berries => bool),
            "minecraft:cave_vines_plant" => try_make!(CaveVinesPlant, state; berries => bool),
            "minecraft:spore_blossom" => Self::SporeBlossom,
            "minecraft:azalea" => Self::Azalea,
            "minecraft:flowering_azalea" => Self::FloweringAzalea,
            "minecraft:moss_carpet" => Self::MossCarpet,
            "minecraft:moss_block" => Self::MossBlock,
            "minecraft:big_dripleaf" => try_make!(BigDripleaf, state; facing => HorizontalDirection, tilt => Tilt, waterlogged => bool),
            "minecraft:big_dripleaf_stem" => try_make!(BigDripleafStem, state; facing => HorizontalDirection, waterlogged => bool),
            "minecraft:small_dripleaf" => try_make!(SmallDripleaf, state; facing => HorizontalDirection, half => DoubleBlockHalf, waterlogged => bool),
            "minecraft:hanging_roots" => try_make!(HangingRoots, state; waterlogged => bool),
            "minecraft:rooted_dirt" => Self::RootedDirt,
            "minecraft:deepslate" => try_make!(Deepslate, state; axis => Axis),
            "minecraft:cobbled_deepslate" => Self::CobbledDeepslate,
            "minecraft:cobbled_deepslate_stairs" => try_make!(CobbledDeepslateStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:cobbled_deepslate_slab" => try_make!(CobbledDeepslateSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:cobbled_deepslate_wall" => try_make!(CobbledDeepslateWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:polished_deepslate" => Self::PolishedDeepslate,
            "minecraft:polished_deepslate_stairs" => try_make!(PolishedDeepslateStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:polished_deepslate_slab" => try_make!(PolishedDeepslateSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:polished_deepslate_wall" => try_make!(PolishedDeepslateWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:deepslate_tiles" => Self::DeepslateTiles,
            "minecraft:deepslate_tile_stairs" => try_make!(DeepslateTileStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:deepslate_tile_slab" => try_make!(DeepslateTileSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:deepslate_tile_wall" => try_make!(DeepslateTileWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:deepslate_bricks" => Self::DeepslateBricks,
            "minecraft:deepslate_brick_stairs" => try_make!(DeepslateBrickStairs, state; facing => HorizontalDirection, half => BlockHalf, shape => StairShape, waterlogged => bool),
            "minecraft:deepslate_brick_slab" => try_make!(DeepslateBrickSlab, state; r#type => SlabType, waterlogged => bool),
            "minecraft:deepslate_brick_wall" => try_make!(DeepslateBrickWall, state; east => WallShape, north => WallShape, south => WallShape, up => bool, waterlogged => bool, west => WallShape),
            "minecraft:chiseled_deepslate" => Self::ChiseledDeepslate,
            "minecraft:cracked_deepslate_bricks" => Self::CrackedDeepslateBricks,
            "minecraft:cracked_deepslate_tiles" => Self::CrackedDeepslateTiles,
            "minecraft:infested_deepslate" => try_make!(InfestedDeepslate, state; axis => Axis),
            "minecraft:smooth_basalt" => Self::SmoothBasalt,
            "minecraft:raw_iron_block" => Self::RawIronBlock,
            "minecraft:raw_copper_block" => Self::RawCopperBlock,
            "minecraft:raw_gold_block" => Self::RawGoldBlock,
            "minecraft:potted_azalea_bush" => Self::PottedAzaleaBush,
            "minecraft:potted_flowering_azalea_bush" => Self::PottedFloweringAzaleaBush,
            _ => Self::Other { name: state.name.to_owned(), properties: state.properties.to_owned() },
        }
    }
}
