on: [push, workflow_dispatch]

name: build

jobs:
  desktop:
    name: rustmatica_desktop
    strategy:
      matrix:
        features: [all, no-default]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Toolchain
        uses: dtolnay/toolchain@stable

      - name: Build
        run: cargo build --release --${{ matrix.features }}-features
  wasm:
    name: rustmatica_wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Toolchain
        uses: dtolnay/toolchain@stable
        with:
          target: wasm32-unknown-unknown

      - name: Build
        run: cargo build --release --all-features --target wasm32-unknown-unknown
