on: [push, workflow_dispatch]

name: build

jobs:
  desktop:
    name: rustmatica_desktop
    strategy:
      matrix:
        features: [all, no-default]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --${{ matrix.features }}-features
  wasm:
    name: rustmatica_wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target wasm32-unknown-unknown
