on: [push]

name: run_tests

jobs:
  linux:
    name: rustmatica_linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run
        uses: actions-rs/cargo@v1
        with:
          command: test
  wasm:
    name: rustmatica_wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Run
        run: wasm-pack test --node --profile wasm-test
