on: [push, workflow_dispatch]

name: tests

jobs:
  all:
    name: rustmatica
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [cargo test --profile no-opt tests::, wasm-pack test --node]
        features: [all, no-default]
    steps:
      - uses: actions/checkout@v3
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
      - name: Run
        run: '${{ matrix.command }} --${{ matrix.features }}-features --lib -- tests::'
